export const worldCurrencies = [
  { label: 'United States dollar (USD)', value: 'USD' },
  { label: 'Canadian dollar (CAD)', value: 'CAD' },
  { label: 'European Euro (EUR)', value: 'EUR' },
  { label: 'Australian dollar (AUD)', value: 'AUD' },
  { label: 'UAE dirham (AED)', value: 'AED' },
  { label: 'Afghan afghani (AFN)', value: 'AFN' },
  { label: 'Albanian lek (ALL)', value: 'ALL' },
  { label: 'Armenian dram (AMD)', value: 'AMD' },
  { label: 'Netherlands Antillean gulden (ANG)', value: 'ANG' },
  { label: 'Angolan kwanza (AOA)', value: 'AOA' },
  { label: 'Argentine peso (ARS)', value: 'ARS' },
  { label: 'Aruban florin (AWG)', value: 'AWG' },
  { label: 'Azerbaijani manat (AZN)', value: 'AZN' },
  { label: 'Bosnia and Herzegovina konvertibilna marka (BAM)', value: 'BAM' },
  { label: 'Barbadian dollar (BBD)', value: 'BBD' },
  { label: 'Bangladeshi taka (BDT)', value: 'BDT' },
  { label: 'Bulgarian lev (BGN)', value: 'BGN' },
  { label: 'Bahraini dinar (BHD)', value: 'BHD' },
  { label: 'Burundi franc (BIF)', value: 'BIF' },
  { label: 'Bermudian dollar (BMD)', value: 'BMD' },
  { label: 'Brunei dollar (BND)', value: 'BND' },
  { label: 'Bolivian boliviano (BOB)', value: 'BOB' },
  { label: 'Brazilian real (BRL)', value: 'BRL' },
  { label: 'Bahamian dollar (BSD)', value: 'BSD' },
  { label: 'Bhutanese ngultrum (BTN)', value: 'BTN' },
  { label: 'Botswana pula (BWP)', value: 'BWP' },
  { label: 'Belarusian ruble (BYR)', value: 'BYR' },
  { label: 'Belize dollar (BZD)', value: 'BZD' },
  { label: 'Congolese franc (CDF)', value: 'CDF' },
  { label: 'Swiss franc (CHF)', value: 'CHF' },
  { label: 'Chilean peso (CLP)', value: 'CLP' },
  { label: 'Chinese/Yuan renminbi (CNY)', value: 'CNY' },
  { label: 'Colombian peso (COP)', value: 'COP' },
  { label: 'Costa Rican colon (CRC)', value: 'CRC' },
  { label: 'Cuban peso (CUC)', value: 'CUC' },
  { label: 'Cape Verdean escudo (CVE)', value: 'CVE' },
  { label: 'Czech koruna (CZK)', value: 'CZK' },
  { label: 'Djiboutian franc (DJF)', value: 'DJF' },
  { label: 'Danish krone (DKK)', value: 'DKK' },
  { label: 'Dominican peso (DOP)', value: 'DOP' },
  { label: 'Algerian dinar (DZD)', value: 'DZD' },
  { label: 'Estonian kroon (EEK)', value: 'EEK' },
  { label: 'Egyptian pound (EGP)', value: 'EGP' },
  { label: 'Eritrean nakfa (ERN)', value: 'ERN' },
  { label: 'Ethiopian birr (ETB)', value: 'ETB' },
  { label: 'Fijian dollar (FJD)', value: 'FJD' },
  { label: 'Falkland Islands pound (FKP)', value: 'FKP' },
  { label: 'British pound (GBP)', value: 'GBP' },
  { label: 'Georgian lari (GEL)', value: 'GEL' },
  { label: 'Ghanaian cedi (GHS)', value: 'GHS' },
  { label: 'Gibraltar pound (GIP)', value: 'GIP' },
  { label: 'Gambian dalasi (GMD)', value: 'GMD' },
  { label: 'Guinean franc (GNF)', value: 'GNF' },
  { label: 'Central African CFA franc (GQE)', value: 'GQE' },
  { label: 'Guatemalan quetzal (GTQ)', value: 'GTQ' },
  { label: 'Guyanese dollar (GYD)', value: 'GYD' },
  { label: 'Hong Kong dollar (HKD)', value: 'HKD' },
  { label: 'Honduran lempira (HNL)', value: 'HNL' },
  { label: 'Croatian kuna (HRK)', value: 'HRK' },
  { label: 'Haitian gourde (HTG)', value: 'HTG' },
  { label: 'Hungarian forint (HUF)', value: 'HUF' },
  { label: 'Indonesian rupiah (IDR)', value: 'IDR' },
  { label: 'Israeli new sheqel (ILS)', value: 'ILS' },
  { label: 'Indian rupee (INR)', value: 'INR' },
  { label: 'Iraqi dinar (IQD)', value: 'IQD' },
  { label: 'Iranian rial (IRR)', value: 'IRR' },
  { label: 'Icelandic króna (ISK)', value: 'ISK' },
  { label: 'Jamaican dollar (JMD)', value: 'JMD' },
  { label: 'Jordanian dinar (JOD)', value: 'JOD' },
  { label: 'Japanese yen (JPY)', value: 'JPY' },
  { label: 'Kenyan shilling (KES)', value: 'KES' },
  { label: 'Kyrgyzstani som (KGS)', value: 'KGS' },
  { label: 'Cambodian riel (KHR)', value: 'KHR' },
  { label: 'Comorian franc (KMF)', value: 'KMF' },
  { label: 'North Korean won (KPW)', value: 'KPW' },
  { label: 'South Korean won (KRW)', value: 'KRW' },
  { label: 'Kuwaiti dinar (KWD)', value: 'KWD' },
  { label: 'Cayman Islands dollar (KYD)', value: 'KYD' },
  { label: 'Kazakhstani tenge (KZT)', value: 'KZT' },
  { label: 'Lao kip (LAK)', value: 'LAK' },
  { label: 'Lebanese lira (LBP)', value: 'LBP' },
  { label: 'Sri Lankan rupee (LKR)', value: 'LKR' },
  { label: 'Liberian dollar (LRD)', value: 'LRD' },
  { label: 'Lesotho loti (LSL)', value: 'LSL' },
  { label: 'Lithuanian litas (LTL)', value: 'LTL' },
  { label: 'Latvian lats (LVL)', value: 'LVL' },
  { label: 'Libyan dinar (LYD)', value: 'LYD' },
  { label: 'Moroccan dirham (MAD)', value: 'MAD' },
  { label: 'Moldovan leu (MDL)', value: 'MDL' },
  { label: 'Malagasy ariary (MGA)', value: 'MGA' },
  { label: 'Macedonian denar (MKD)', value: 'MKD' },
  { label: 'Myanma kyat (MMK)', value: 'MMK' },
  { label: 'Mongolian tugrik (MNT)', value: 'MNT' },
  { label: 'Macanese pataca (MOP)', value: 'MOP' },
  { label: 'Mauritanian ouguiya (MRO)', value: 'MRO' },
  { label: 'Mauritian rupee (MUR)', value: 'MUR' },
  { label: 'Maldivian rufiyaa (MVR)', value: 'MVR' },
  { label: 'Malawian kwacha (MWK)', value: 'MWK' },
  { label: 'Mexican peso (MXN)', value: 'MXN' },
  { label: 'Malaysian ringgit (MYR)', value: 'MYR' },
  { label: 'Mozambican metical (MZM)', value: 'MZM' },
  { label: 'Namibian dollar (NAD)', value: 'NAD' },
  { label: 'Nigerian naira (NGN)', value: 'NGN' },
  { label: 'Nicaraguan córdoba (NIO)', value: 'NIO' },
  { label: 'Norwegian krone (NOK)', value: 'NOK' },
  { label: 'Nepalese rupee (NPR)', value: 'NPR' },
  { label: 'New Zealand dollar (NZD)', value: 'NZD' },
  { label: 'Omani rial (OMR)', value: 'OMR' },
  { label: 'Panamanian balboa (PAB)', value: 'PAB' },
  { label: 'Peruvian nuevo sol (PEN)', value: 'PEN' },
  { label: 'Papua New Guinean kina (PGK)', value: 'PGK' },
  { label: 'Philippine peso (PHP)', value: 'PHP' },
  { label: 'Pakistani rupee (PKR)', value: 'PKR' },
  { label: 'Polish zloty (PLN)', value: 'PLN' },
  { label: 'Paraguayan guarani (PYG)', value: 'PYG' },
  { label: 'Qatari riyal (QAR)', value: 'QAR' },
  { label: 'Romanian leu (RON)', value: 'RON' },
  { label: 'Serbian dinar (RSD)', value: 'RSD' },
  { label: 'Russian ruble (RUB)', value: 'RUB' },
  { label: 'Saudi riyal (SAR)', value: 'SAR' },
  { label: 'Solomon Islands dollar (SBD)', value: 'SBD' },
  { label: 'Seychellois rupee (SCR)', value: 'SCR' },
  { label: 'Sudanese pound (SDG)', value: 'SDG' },
  { label: 'Swedish krona (SEK)', value: 'SEK' },
  { label: 'Singapore dollar (SGD)', value: 'SGD' },
  { label: 'Saint Helena pound (SHP)', value: 'SHP' },
  { label: 'Sierra Leonean leone (SLL)', value: 'SLL' },
  { label: 'Somali shilling (SOS)', value: 'SOS' },
  { label: 'Surinamese dollar (SRD)', value: 'SRD' },
  { label: 'Syrian pound (SYP)', value: 'SYP' },
  { label: 'Swazi lilangeni (SZL)', value: 'SZL' },
  { label: 'Thai baht (THB)', value: 'THB' },
  { label: 'Tajikistani somoni (TJS)', value: 'TJS' },
  { label: 'Turkmen manat (TMT)', value: 'TMT' },
  { label: 'Tunisian dinar (TND)', value: 'TND' },
  { label: 'Turkish new lira (TRY)', value: 'TRY' },
  { label: 'Trinidad and Tobago dollar (TTD)', value: 'TTD' },
  { label: 'New Taiwan dollar (TWD)', value: 'TWD' },
  { label: 'Tanzanian shilling (TZS)', value: 'TZS' },
  { label: 'Ukrainian hryvnia (UAH)', value: 'UAH' },
  { label: 'Ugandan shilling (UGX)', value: 'UGX' },
  { label: 'Uruguayan peso (UYU)', value: 'UYU' },
  { label: 'Uzbekistani som (UZS)', value: 'UZS' },
  { label: 'Venezuelan bolivar (VEB)', value: 'VEB' },
  { label: 'Vietnamese dong (VND)', value: 'VND' },
  { label: 'Vanuatu vatu (VUV)', value: 'VUV' },
  { label: 'Samoan tala (WST)', value: 'WST' },
  { label: 'Central African CFA franc (XAF)', value: 'XAF' },
  { label: 'East Caribbean dollar (XCD)', value: 'XCD' },
  { label: 'Special Drawing Rights (XDR)', value: 'XDR' },
  { label: 'West African CFA franc (XOF)', value: 'XOF' },
  { label: 'CFP franc (XPF)', value: 'XPF' },
  { label: 'Yemeni rial (YER)', value: 'YER' },
  { label: 'South African rand (ZAR)', value: 'ZAR' },
  { label: 'Zambian kwacha (ZMK)', value: 'ZMK' },
  { label: 'Zimbabwean dollar (ZWR)', value: 'ZWR' },
];
