export const worldCurrencies = [
  { label: "United States dollar (USD)", value: "USD" },
  { label: "Canadian dollar (CAD)", value: "CAD" },
  { label: "European Euro (EUR)", value: "EUR" },
  { label: "British pound (GBP)", value: "GBP" },
  { label: "Australian dollar (AUD)", value: "AUD" },
  { label: "Hong Kong dollar (HKD)", value: "HKD" },
  { label: "Singapore dollar (SGD)", value: "SGD" },
  { label: "Japanese yen (JPY)", value: "JPY" },
  { label: "Swiss franc (CHF)", value: "CHF" },
  { label: "Chinese/Yuan renminbi (CNY)", value: "CNY" },
  { label: "South Korean won (KRW)", value: "KRW" },
  { label: "Indian rupee (INR)", value: "INR" },
  { label: "Brazilian real (BRL)", value: "BRL" },
  { label: "Russian ruble (RUB)", value: "RUB" },
  { label: "South African rand (ZAR)", value: "ZAR" },
  { label: "New Zealand dollar (NZD)", value: "NZD" },
  { label: "Norwegian krone (NOK)", value: "NOK" },
  { label: "Swedish krona (SEK)", value: "SEK" },
  { label: "Danish krone (DKK)", value: "DKK" },
  { label: "Polish zloty (PLN)", value: "PLN" },
  { label: "Turkish lira (TRY)", value: "TRY" },
  { label: "Israeli new sheqel (ILS)", value: "ILS" },
  { label: "Mexican peso (MXN)", value: "MXN" },
  { label: "New Taiwan dollar (TWD)", value: "TWD" },
  { label: "Argentine peso (ARS)", value: "ARS" },

  { label: "Afghan afghani (AFN)", value: "AFN" },
  { label: "Albanian lek (ALL)", value: "ALL" },
  { label: "Algerian dinar (DZD)", value: "DZD" },
  { label: "Angolan kwanza (AOA)", value: "AOA" },
  { label: "Armenian dram (AMD)", value: "AMD" },
  { label: "Aruban florin (AWG)", value: "AWG" },
  { label: "Azerbaijani manat (AZN)", value: "AZN" },
  { label: "Bahamian dollar (BSD)", value: "BSD" },
  { label: "Bahraini dinar (BHD)", value: "BHD" },
  { label: "Bangladeshi taka (BDT)", value: "BDT" },
  { label: "Barbadian dollar (BBD)", value: "BBD" },
  { label: "Belarusian ruble (BYR)", value: "BYR" },
  { label: "Belize dollar (BZD)", value: "BZD" },
  { label: "Bermudian dollar (BMD)", value: "BMD" },
  { label: "Bhutanese ngultrum (BTN)", value: "BTN" },
  { label: "Bolivian boliviano (BOB)", value: "BOB" },
  {
    label: "Bosnia and Herzegovina konvertibilna marka (BAM)",
    value: "BAM",
  },
  { label: "Botswana pula (BWP)", value: "BWP" },
  { label: "Brunei dollar (BND)", value: "BND" },
  { label: "Bulgarian lev (BGN)", value: "BGN" },
  { label: "Burundi franc (BIF)", value: "BIF" },
  { label: "Cambodian riel (KHR)", value: "KHR" },
  { label: "Cape Verdean escudo (CVE)", value: "CVE" },
  { label: "Cayman Islands dollar (KYD)", value: "KYD" },
  { label: "Central African CFA franc (GQE)", value: "GQE" },
  { label: "Central African CFA franc (XAF)", value: "XAF" },
  { label: "CFP franc (XPF)", value: "XPF" },
  { label: "Chilean peso (CLP)", value: "CLP" },
  { label: "Colombian peso (COP)", value: "COP" },
  { label: "Comorian franc (KMF)", value: "KMF" },
  { label: "Congolese franc (CDF)", value: "CDF" },
  { label: "Costa Rican colon (CRC)", value: "CRC" },
  { label: "Croatian kuna (HRK)", value: "HRK" },
  { label: "Cuban peso (CUC)", value: "CUC" },
  { label: "Czech koruna (CZK)", value: "CZK" },
  { label: "Djiboutian franc (DJF)", value: "DJF" },
  { label: "Dominican peso (DOP)", value: "DOP" },
  { label: "East Caribbean dollar (XCD)", value: "XCD" },
  { label: "Egyptian pound (EGP)", value: "EGP" },
  { label: "Eritrean nakfa (ERN)", value: "ERN" },
  { label: "Estonian kroon (EEK)", value: "EEK" },
  { label: "Ethiopian birr (ETB)", value: "ETB" },
  { label: "Falkland Islands pound (FKP)", value: "FKP" },
  { label: "Fijian dollar (FJD)", value: "FJD" },
  { label: "Gambian dalasi (GMD)", value: "GMD" },
  { label: "Georgian lari (GEL)", value: "GEL" },
  { label: "Ghanaian cedi (GHS)", value: "GHS" },
  { label: "Gibraltar pound (GIP)", value: "GIP" },
  { label: "Guatemalan quetzal (GTQ)", value: "GTQ" },
  { label: "Guinean franc (GNF)", value: "GNF" },
  { label: "Guyanese dollar (GYD)", value: "GYD" },
  { label: "Haitian gourde (HTG)", value: "HTG" },
  { label: "Honduran lempira (HNL)", value: "HNL" },
  { label: "Hungarian forint (HUF)", value: "HUF" },
  { label: "Icelandic króna (ISK)", value: "ISK" },
  { label: "Indonesian rupiah (IDR)", value: "IDR" },
  { label: "Iranian rial (IRR)", value: "IRR" },
  { label: "Iraqi dinar (IQD)", value: "IQD" },
  { label: "Jamaican dollar (JMD)", value: "JMD" },
  { label: "Jordanian dinar (JOD)", value: "JOD" },
  { label: "Kazakhstani tenge (KZT)", value: "KZT" },
  { label: "Kenyan shilling (KES)", value: "KES" },
  { label: "Kuwaiti dinar (KWD)", value: "KWD" },
  { label: "Kyrgyzstani som (KGS)", value: "KGS" },
  { label: "Lao kip (LAK)", value: "LAK" },
  { label: "Latvian lats (LVL)", value: "LVL" },
  { label: "Lebanese lira (LBP)", value: "LBP" },
  { label: "Lesotho loti (LSL)", value: "LSL" },
  { label: "Liberian dollar (LRD)", value: "LRD" },
  { label: "Libyan dinar (LYD)", value: "LYD" },
  { label: "Lithuanian litas (LTL)", value: "LTL" },
  { label: "Macanese pataca (MOP)", value: "MOP" },
  { label: "Macedonian denar (MKD)", value: "MKD" },
  { label: "Malagasy ariary (MGA)", value: "MGA" },
  { label: "Malawian kwacha (MWK)", value: "MWK" },
  { label: "Malaysian ringgit (MYR)", value: "MYR" },
  { label: "Maldivian rufiyaa (MVR)", value: "MVR" },
  { label: "Mauritanian ouguiya (MRO)", value: "MRO" },
  { label: "Mauritian rupee (MUR)", value: "MUR" },
  { label: "Moldovan leu (MDL)", value: "MDL" },
  { label: "Mongolian tugrik (MNT)", value: "MNT" },
  { label: "Moroccan dirham (MAD)", value: "MAD" },
  { label: "Mozambican metical (MZM)", value: "MZM" },
  { label: "Myanma kyat (MMK)", value: "MMK" },
  { label: "Namibian dollar (NAD)", value: "NAD" },
  { label: "Nepalese rupee (NPR)", value: "NPR" },
  { label: "Netherlands Antillean gulden (ANG)", value: "ANG" },
  { label: "Nicaraguan córdoba (NIO)", value: "NIO" },
  { label: "Nigerian naira (NGN)", value: "NGN" },
  { label: "North Korean won (KPW)", value: "KPW" },
  { label: "Omani rial (OMR)", value: "OMR" },
  { label: "Pakistani rupee (PKR)", value: "PKR" },
  { label: "Panamanian balboa (PAB)", value: "PAB" },
  { label: "Papua New Guinean kina (PGK)", value: "PGK" },
  { label: "Paraguayan guarani (PYG)", value: "PYG" },
  { label: "Peruvian nuevo sol (PEN)", value: "PEN" },
  { label: "Philippine peso (PHP)", value: "PHP" },
  { label: "Qatari riyal (QAR)", value: "QAR" },
  { label: "Romanian leu (RON)", value: "RON" },
  { label: "Saint Helena pound (SHP)", value: "SHP" },
  { label: "Samoan tala (WST)", value: "WST" },
  { label: "Saudi riyal (SAR)", value: "SAR" },
  { label: "Serbian dinar (RSD)", value: "RSD" },
  { label: "Seychellois rupee (SCR)", value: "SCR" },
  { label: "Sierra Leonean leone (SLL)", value: "SLL" },
  { label: "Solomon Islands dollar (SBD)", value: "SBD" },
  { label: "Somali shilling (SOS)", value: "SOS" },
  { label: "Special Drawing Rights (XDR)", value: "XDR" },
  { label: "Sri Lankan rupee (LKR)", value: "LKR" },
  { label: "Sudanese pound (SDG)", value: "SDG" },
  { label: "Surinamese dollar (SRD)", value: "SRD" },
  { label: "Swazi lilangeni (SZL)", value: "SZL" },
  { label: "Syrian pound (SYP)", value: "SYP" },
  { label: "Tajikistani somoni (TJS)", value: "TJS" },
  { label: "Tanzanian shilling (TZS)", value: "TZS" },
  { label: "Thai baht (THB)", value: "THB" },
  { label: "Trinidad and Tobago dollar (TTD)", value: "TTD" },
  { label: "Tunisian dinar (TND)", value: "TND" },
  { label: "Turkmen manat (TMT)", value: "TMT" },
  { label: "UAE dirham (AED)", value: "AED" },
  { label: "Ugandan shilling (UGX)", value: "UGX" },
  { label: "Ukrainian hryvnia (UAH)", value: "UAH" },
  { label: "Uruguayan peso (UYU)", value: "UYU" },
  { label: "Uzbekistani som (UZS)", value: "UZS" },
  { label: "Vanuatu vatu (VUV)", value: "VUV" },
  { label: "Venezuelan bolivar (VEB)", value: "VEB" },
  { label: "Vietnamese dong (VND)", value: "VND" },
  { label: "West African CFA franc (XOF)", value: "XOF" },
  { label: "Yemeni rial (YER)", value: "YER" },
  { label: "Zambian kwacha (ZMK)", value: "ZMK" },
  { label: "Zimbabwean dollar (ZWR)", value: "ZWR" },
];
