//! Asset ID utilities.
//!
//! With v2, asset IDs are opaque UUIDs generated by the database.
//! This module retains only symbol parsing helpers needed by other modules.
//! The typed prefix ID system (SEC:AAPL:XNAS) is removed.

use wealthfolio_market_data::{
    mic_to_currency, strip_yahoo_suffix, yahoo_exchange_suffixes, yahoo_suffix_to_mic,
};

/// Parse crypto pair symbols like "BTC-USD" or "BTC-USDT" into (base, quote).
/// Returns None if the symbol doesn't match the expected pair pattern.
pub fn parse_crypto_pair_symbol(symbol: &str) -> Option<(String, String)> {
    let trimmed = symbol.trim();
    let (base, quote) = trimmed.rsplit_once('-')?;
    let base = base.trim();
    let quote = quote.trim();
    if base.is_empty() || quote.is_empty() {
        return None;
    }
    let quote_upper = quote.to_uppercase();
    let quote_len = quote_upper.len();
    if !(3..=5).contains(&quote_len) || !quote_upper.chars().all(|c| c.is_ascii_alphabetic()) {
        return None;
    }
    Some((base.to_string(), quote_upper))
}

/// Parses a symbol that may contain a Yahoo Finance exchange suffix and extracts
/// the base symbol and exchange MIC.
///
/// Yahoo Finance uses suffixes like `.TO` (Toronto), `.L` (London), `.DE` (XETRA)
/// to indicate the exchange. This function strips the suffix and maps it to the
/// canonical MIC (Market Identifier Code).
///
/// # Returns
///
/// A tuple of (base_symbol, Option<mic>):
/// - `base_symbol`: The symbol without the suffix (e.g., "SHOP", "VOD", "AAPL")
/// - `mic`: The exchange MIC if a known suffix was found (e.g., Some("XTSE"), Some("XLON"), None)
pub fn parse_symbol_with_exchange_suffix(symbol: &str) -> (&str, Option<&'static str>) {
    let trimmed = symbol.trim();
    let base_symbol = strip_yahoo_suffix(trimmed);

    let mic = trimmed
        .get(base_symbol.len()..)
        .and_then(|suffix| suffix.strip_prefix('.'))
        .and_then(yahoo_suffix_to_mic);

    (base_symbol, mic)
}

/// Parse a symbol's exchange suffix when the venue is already known.
///
/// [`parse_symbol_with_exchange_suffix`] cannot tell an exchange suffix from a
/// ticker that merely ends in one — the symbol alone carries nothing to check
/// against. When the caller already knows the venue, that is the better evidence,
/// and a suffix that names a market the instrument cannot be trading on was never
/// a venue marker.
///
/// `ZAAA.F` on `NEOE` is the case that motivated this: BMO's currency-hedged unit
/// class on Cboe Canada, where `.F` is Yahoo's Frankfurt suffix. Stripping it files
/// the holding under `ZAAA` — the *unhedged* listing, a real security quoting ~4%
/// away — and nothing downstream can notice, because the shortened ticker resolves
/// a perfectly valid quote for the wrong fund. Observed live on 2026-07-30 in 33
/// activity records from a real brokerage.
///
/// A merely *different* MIC is not enough to rule a suffix out, so two guards keep
/// the rule narrow:
///
/// - **The known venue must be a MIC the registry recognises.** Brokers send
///   exchange labels that are not MICs at all (`NEO`, `NMS`), and the sync paths
///   pass one through as the venue when the symbol has no suffix to read. Junk must
///   not silence a good suffix.
/// - **The two venues must trade in different currencies.** `XETR` (`.DE`) and
///   `XFRA` (`.F`) are separate registry entries for the same German listing, and a
///   caller naming one while the symbol carries the other is choosing a venue, not
///   spelling a share class. Keeping `.DE` on the ticker there would resolve the
///   provider symbol `BMW-DE.F`, which does not exist. A different currency means a
///   different market, and `.F` on a CAD venue cannot be Frankfurt.
///
/// With no known venue, or one the suffix agrees with, this is
/// [`parse_symbol_with_exchange_suffix`]. A share class whose suffix is not a known
/// venue at all (`BRK.B`) never reaches either rule.
///
/// # Returns
///
/// `(base_symbol, mic)` as above, except that a contradicted suffix is left on the
/// symbol and reported as no MIC — the caller's own venue is the answer.
pub fn parse_symbol_with_known_exchange<'a>(
    symbol: &'a str,
    known_mic: Option<&str>,
) -> (&'a str, Option<&'static str>) {
    let (base_symbol, suffix_mic) = parse_symbol_with_exchange_suffix(symbol);

    let Some(parsed_mic) = suffix_mic else {
        return (base_symbol, None);
    };
    let Some(known) = known_mic.map(str::trim).filter(|mic| !mic.is_empty()) else {
        return (base_symbol, Some(parsed_mic));
    };
    if known.eq_ignore_ascii_case(parsed_mic) {
        return (base_symbol, Some(parsed_mic));
    }

    // Both lookups have to land for the venues to disagree about anything: an
    // unrecognised MIC carries no evidence, and same-currency venues are the same
    // market listing the same security.
    let contradicted = match (
        mic_to_currency(&known.to_uppercase()),
        mic_to_currency(parsed_mic),
    ) {
        (Some(known_ccy), Some(suffix_ccy)) => !known_ccy.eq_ignore_ascii_case(suffix_ccy),
        _ => false,
    };

    if contradicted {
        (symbol.trim(), None)
    } else {
        (base_symbol, Some(parsed_mic))
    }
}

/// Returns a best-effort fallback base symbol for unknown dotted suffixes.
///
/// Examples:
/// - "VWRPL.XC" -> Some("VWRPL")
/// - "SHOP.TO" -> None (known exchange suffix, handled elsewhere)
/// - "BRK.B" -> None (share class suffix should be preserved)
pub fn unknown_dotted_suffix_fallback(symbol: &str) -> Option<&str> {
    let trimmed = symbol.trim();
    let (base, suffix) = trimmed.rsplit_once('.')?;
    if base.is_empty() || suffix.is_empty() {
        return None;
    }

    // Keep single-letter share class suffixes (e.g., BRK.B) intact.
    if suffix.len() == 1 {
        return None;
    }

    // Only consider alphabetic suffixes with plausible exchange-like lengths.
    if !(2..=5).contains(&suffix.len()) || !suffix.chars().all(|c| c.is_ascii_alphabetic()) {
        return None;
    }

    // Known Yahoo exchange suffixes are already handled by parse_symbol_with_exchange_suffix.
    let is_known_suffix = yahoo_exchange_suffixes().iter().any(|known| {
        let known_without_dot = known.strip_prefix('.').unwrap_or(known);
        known_without_dot.eq_ignore_ascii_case(suffix)
    });
    if is_known_suffix || yahoo_suffix_to_mic(&suffix.to_uppercase()).is_some() {
        return None;
    }

    Some(base)
}

/// Returns symbol resolution candidates in precedence order:
/// 1) Raw symbol as provided
/// 2) Unknown dotted-suffix fallback (e.g. VWRPL.XC -> VWRPL), when applicable
pub fn symbol_resolution_candidates(symbol: &str) -> Vec<String> {
    let trimmed = symbol.trim();
    if trimmed.is_empty() {
        return vec![];
    }

    let mut candidates = vec![trimmed.to_string()];
    if let Some(fallback) = unknown_dotted_suffix_fallback(trimmed) {
        if !fallback.eq_ignore_ascii_case(trimmed) {
            candidates.push(fallback.to_string());
        }
    }
    candidates
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_crypto_pair_symbol() {
        assert_eq!(
            parse_crypto_pair_symbol("BTC-USD"),
            Some(("BTC".to_string(), "USD".to_string()))
        );
        assert_eq!(
            parse_crypto_pair_symbol("BTC-USDT"),
            Some(("BTC".to_string(), "USDT".to_string()))
        );
        assert_eq!(
            parse_crypto_pair_symbol("X-AI-USD"),
            Some(("X-AI".to_string(), "USD".to_string()))
        );
        assert_eq!(parse_crypto_pair_symbol("BTCUSD"), None);
        assert_eq!(parse_crypto_pair_symbol("BTC"), None);
    }

    #[test]
    fn test_parse_symbol_with_exchange_suffix() {
        let (symbol, mic) = parse_symbol_with_exchange_suffix("SHOP.TO");
        assert_eq!(symbol, "SHOP");
        assert_eq!(mic, Some("XTSE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("APC.DE");
        assert_eq!(symbol, "APC");
        assert_eq!(mic, Some("XETR"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("shop.to");
        assert_eq!(symbol, "shop");
        assert_eq!(mic, Some("XTSE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("VOD.L");
        assert_eq!(symbol, "VOD");
        assert_eq!(mic, Some("XLON"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("WSLV.MI");
        assert_eq!(symbol, "WSLV");
        assert_eq!(mic, Some("XMIL"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("BRK.B.TO");
        assert_eq!(symbol, "BRK.B");
        assert_eq!(mic, Some("XTSE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("vwrpl.xc");
        assert_eq!(symbol, "vwrpl");
        assert_eq!(mic, Some("BCXE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("AAPL");
        assert_eq!(symbol, "AAPL");
        assert_eq!(mic, None);

        // Share class suffixes (not exchange suffixes) are preserved
        let (symbol, mic) = parse_symbol_with_exchange_suffix("BRK.B");
        assert_eq!(symbol, "BRK.B");
        assert_eq!(mic, None);
    }

    #[test]
    fn test_parse_symbol_with_exchange_suffix_handles_non_ascii_symbols() {
        for symbol in ["ÅÄÖ", "سهم", "東京", "😀"] {
            assert_eq!(parse_symbol_with_exchange_suffix(symbol), (symbol, None));

            let suffixed = format!("{symbol}.TO");
            assert_eq!(
                parse_symbol_with_exchange_suffix(&suffixed),
                (symbol, Some("XTSE"))
            );
        }
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_without_a_venue_is_the_plain_rule() {
        for symbol in ["SHOP.TO", "BRK.B", "AAPL", "ZAAA.F"] {
            assert_eq!(
                parse_symbol_with_known_exchange(symbol, None),
                parse_symbol_with_exchange_suffix(symbol),
                "{symbol} with no venue must parse exactly as it always did"
            );
            // Blank and whitespace-only venues are no venue at all.
            for blank in ["", "   "] {
                assert_eq!(
                    parse_symbol_with_known_exchange(symbol, Some(blank)),
                    parse_symbol_with_exchange_suffix(symbol),
                    "{symbol} with a blank venue must parse as if none were given"
                );
            }
        }
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_strips_when_the_venue_agrees() {
        // Agreement is checked case- and whitespace-insensitively.
        for known in ["XTSE", "xtse", "  XTSE  "] {
            assert_eq!(
                parse_symbol_with_known_exchange("SHOP.TO", Some(known)),
                ("SHOP", Some("XTSE"))
            );
        }
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_keeps_a_suffix_from_another_currency() {
        // `.F` is Frankfurt (EUR); Cboe Canada (NEOE) trades in CAD. BMO's `ZAAA.F`
        // is the hedged unit class, so the suffix belongs to the ticker.
        assert_eq!(
            parse_symbol_with_known_exchange("ZAAA.F", Some("NEOE")),
            ("ZAAA.F", None)
        );
        assert_eq!(
            parse_symbol_with_known_exchange("  ZAAA.F  ", Some("neoe")),
            ("ZAAA.F", None)
        );
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_strips_for_a_sibling_venue() {
        // XETR and XFRA are two German entries for the same listing, so a caller
        // naming one while the symbol carries the other is picking a venue rather
        // than spelling a share class. Stripping keeps the provider symbol real:
        // `BMW` + XFRA resolves `BMW.F`, where `BMW.DE` would resolve `BMW-DE.F`.
        assert_eq!(
            parse_symbol_with_known_exchange("BMW.DE", Some("XFRA")),
            ("BMW", Some("XETR"))
        );
        assert_eq!(
            parse_symbol_with_known_exchange("BMW.F", Some("XETR")),
            ("BMW", Some("XFRA"))
        );
        // Same market, same currency, different Canadian venue.
        assert_eq!(
            parse_symbol_with_known_exchange("SHOP.TO", Some("XTSX")),
            ("SHOP", Some("XTSE"))
        );
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_ignores_a_venue_that_is_not_a_mic() {
        // Brokers label exchanges with their own abbreviations (`NEO` for Cboe
        // Canada, whose MIC is NEOE), and the sync paths pass one through as the
        // venue. None of them may silence a suffix that does resolve.
        for junk in ["NEO", "TSX", "NASDAQ", "not-a-mic"] {
            assert_eq!(
                parse_symbol_with_known_exchange("SHOP.TO", Some(junk)),
                ("SHOP", Some("XTSE")),
                "{junk} is not a MIC and must not override the suffix"
            );
        }
    }

    #[test]
    fn test_parse_symbol_with_known_exchange_leaves_unsuffixed_symbols_alone() {
        // No suffix to argue about, whatever the venue says.
        assert_eq!(
            parse_symbol_with_known_exchange("AAPL", Some("NEOE")),
            ("AAPL", None)
        );
        // `.B` is not in the Yahoo suffix table, so no rule reaches it.
        assert_eq!(
            parse_symbol_with_known_exchange("BRK.B", Some("XNYS")),
            ("BRK.B", None)
        );
    }

    #[test]
    fn test_unknown_dotted_suffix_fallback() {
        // .XC is now a known Yahoo exchange suffix (Cboe UK), so no unknown fallback.
        assert_eq!(unknown_dotted_suffix_fallback("VWRPL.XC"), None);
        assert_eq!(unknown_dotted_suffix_fallback("foo.ae"), None);
        assert_eq!(unknown_dotted_suffix_fallback("SHOP.TO"), None);
        assert_eq!(unknown_dotted_suffix_fallback("BRK.B"), None);
        assert_eq!(unknown_dotted_suffix_fallback("AAPL"), None);
    }

    #[test]
    fn test_symbol_resolution_candidates() {
        assert_eq!(
            symbol_resolution_candidates("VWRPL.XC"),
            vec!["VWRPL.XC".to_string()]
        );
        assert_eq!(
            symbol_resolution_candidates("SHOP.TO"),
            vec!["SHOP.TO".to_string()]
        );
        assert_eq!(symbol_resolution_candidates(""), Vec::<String>::new());
    }
}
