//! Asset ID utilities.
//!
//! With v2, asset IDs are opaque UUIDs generated by the database.
//! This module retains only symbol parsing helpers needed by other modules.
//! The typed prefix ID system (SEC:AAPL:XNAS) is removed.

use wealthfolio_market_data::{strip_yahoo_suffix, yahoo_exchange_suffixes, yahoo_suffix_to_mic};

/// Parse crypto pair symbols like "BTC-USD" or "BTC-USDT" into (base, quote).
/// Returns None if the symbol doesn't match the expected pair pattern.
pub fn parse_crypto_pair_symbol(symbol: &str) -> Option<(String, String)> {
    let trimmed = symbol.trim();
    let (base, quote) = trimmed.rsplit_once('-')?;
    let base = base.trim();
    let quote = quote.trim();
    if base.is_empty() || quote.is_empty() {
        return None;
    }
    let quote_upper = quote.to_uppercase();
    let quote_len = quote_upper.len();
    if !(3..=5).contains(&quote_len) || !quote_upper.chars().all(|c| c.is_ascii_alphabetic()) {
        return None;
    }
    Some((base.to_string(), quote_upper))
}

/// Parses a symbol that may contain a Yahoo Finance exchange suffix and extracts
/// the base symbol and exchange MIC.
///
/// Yahoo Finance uses suffixes like `.TO` (Toronto), `.L` (London), `.DE` (XETRA)
/// to indicate the exchange. This function strips the suffix and maps it to the
/// canonical MIC (Market Identifier Code).
///
/// # Returns
///
/// A tuple of (base_symbol, Option<mic>):
/// - `base_symbol`: The symbol without the suffix (e.g., "SHOP", "VOD", "AAPL")
/// - `mic`: The exchange MIC if a known suffix was found (e.g., Some("XTSE"), Some("XLON"), None)
pub fn parse_symbol_with_exchange_suffix(symbol: &str) -> (&str, Option<&'static str>) {
    let trimmed = symbol.trim();
    let base_symbol = strip_yahoo_suffix(trimmed);

    let mic = yahoo_exchange_suffixes()
        .iter()
        .find(|suffix| {
            trimmed.len() >= suffix.len()
                && trimmed[trimmed.len() - suffix.len()..].eq_ignore_ascii_case(suffix)
        })
        .and_then(|suffix| yahoo_suffix_to_mic(&suffix[1..]));

    (base_symbol, mic)
}

/// Returns a best-effort fallback base symbol for unknown dotted suffixes.
///
/// Examples:
/// - "VWRPL.XC" -> Some("VWRPL")
/// - "SHOP.TO" -> None (known exchange suffix, handled elsewhere)
/// - "BRK.B" -> None (share class suffix should be preserved)
pub fn unknown_dotted_suffix_fallback(symbol: &str) -> Option<&str> {
    let trimmed = symbol.trim();
    let (base, suffix) = trimmed.rsplit_once('.')?;
    if base.is_empty() || suffix.is_empty() {
        return None;
    }

    // Keep single-letter share class suffixes (e.g., BRK.B) intact.
    if suffix.len() == 1 {
        return None;
    }

    // Only consider alphabetic suffixes with plausible exchange-like lengths.
    if !(2..=5).contains(&suffix.len()) || !suffix.chars().all(|c| c.is_ascii_alphabetic()) {
        return None;
    }

    // Known Yahoo exchange suffixes are already handled by parse_symbol_with_exchange_suffix.
    let is_known_suffix = yahoo_exchange_suffixes().iter().any(|known| {
        let known_without_dot = known.strip_prefix('.').unwrap_or(known);
        known_without_dot.eq_ignore_ascii_case(suffix)
    });
    if is_known_suffix || yahoo_suffix_to_mic(&suffix.to_uppercase()).is_some() {
        return None;
    }

    Some(base)
}

/// Returns symbol resolution candidates in precedence order:
/// 1) Raw symbol as provided
/// 2) Unknown dotted-suffix fallback (e.g. VWRPL.XC -> VWRPL), when applicable
pub fn symbol_resolution_candidates(symbol: &str) -> Vec<String> {
    let trimmed = symbol.trim();
    if trimmed.is_empty() {
        return vec![];
    }

    let mut candidates = vec![trimmed.to_string()];
    if let Some(fallback) = unknown_dotted_suffix_fallback(trimmed) {
        if !fallback.eq_ignore_ascii_case(trimmed) {
            candidates.push(fallback.to_string());
        }
    }
    candidates
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_crypto_pair_symbol() {
        assert_eq!(
            parse_crypto_pair_symbol("BTC-USD"),
            Some(("BTC".to_string(), "USD".to_string()))
        );
        assert_eq!(
            parse_crypto_pair_symbol("BTC-USDT"),
            Some(("BTC".to_string(), "USDT".to_string()))
        );
        assert_eq!(
            parse_crypto_pair_symbol("X-AI-USD"),
            Some(("X-AI".to_string(), "USD".to_string()))
        );
        assert_eq!(parse_crypto_pair_symbol("BTCUSD"), None);
        assert_eq!(parse_crypto_pair_symbol("BTC"), None);
    }

    #[test]
    fn test_parse_symbol_with_exchange_suffix() {
        let (symbol, mic) = parse_symbol_with_exchange_suffix("SHOP.TO");
        assert_eq!(symbol, "SHOP");
        assert_eq!(mic, Some("XTSE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("shop.to");
        assert_eq!(symbol, "shop");
        assert_eq!(mic, Some("XTSE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("VOD.L");
        assert_eq!(symbol, "VOD");
        assert_eq!(mic, Some("XLON"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("vwrpl.xc");
        assert_eq!(symbol, "vwrpl");
        assert_eq!(mic, Some("CXE"));

        let (symbol, mic) = parse_symbol_with_exchange_suffix("AAPL");
        assert_eq!(symbol, "AAPL");
        assert_eq!(mic, None);

        // Share class suffixes (not exchange suffixes) are preserved
        let (symbol, mic) = parse_symbol_with_exchange_suffix("BRK.B");
        assert_eq!(symbol, "BRK.B");
        assert_eq!(mic, None);
    }

    #[test]
    fn test_unknown_dotted_suffix_fallback() {
        // .XC is now a known Yahoo exchange suffix (Cboe UK), so no unknown fallback.
        assert_eq!(unknown_dotted_suffix_fallback("VWRPL.XC"), None);
        assert_eq!(unknown_dotted_suffix_fallback("foo.ae"), None);
        assert_eq!(unknown_dotted_suffix_fallback("SHOP.TO"), None);
        assert_eq!(unknown_dotted_suffix_fallback("BRK.B"), None);
        assert_eq!(unknown_dotted_suffix_fallback("AAPL"), None);
    }

    #[test]
    fn test_symbol_resolution_candidates() {
        assert_eq!(
            symbol_resolution_candidates("VWRPL.XC"),
            vec!["VWRPL.XC".to_string()]
        );
        assert_eq!(
            symbol_resolution_candidates("SHOP.TO"),
            vec!["SHOP.TO".to_string()]
        );
        assert_eq!(symbol_resolution_candidates(""), Vec::<String>::new());
    }
}
