use super::holdings_calculator::HoldingsCalculator;
use super::SnapshotRepositoryTrait;
use crate::accounts::{Account, AccountRepositoryTrait, TrackingMode};
use crate::activities::{
    Activity, ActivityCompiler, ActivityRepositoryTrait, DefaultActivityCompiler,
};
use crate::assets::AssetRepositoryTrait;
use crate::constants::{DECIMAL_PRECISION, PORTFOLIO_TOTAL_ACCOUNT_ID};
use crate::errors::{CalculatorError, Error, Result};
use crate::events::{DomainEvent, DomainEventSink, NoOpDomainEventSink};
use crate::fx::FxServiceTrait;
use crate::lots::{
    check_lot_quantity_consistency, extract_lot_records, DisposalMethod, LotRecord,
    LotRepositoryTrait,
};
use crate::portfolio::snapshot::{
    AccountStateSnapshot, HoldingsCalculationWarning, SnapshotSource,
};
use crate::utils::time_utils::{
    activity_date_in_tz, get_days_between, parse_user_timezone_or_default, user_today,
};

use async_trait::async_trait;
use chrono::{Months, NaiveDate, Utc};
use log::{debug, error, info, warn};
use rust_decimal::Decimal;
use std::collections::{BTreeMap, HashMap, HashSet, VecDeque};
use std::sync::{Arc, RwLock};

// --- Recalculation mode ---

/// Controls the scope of a holdings snapshot recalculation.
#[derive(Clone, Debug)]
pub enum SnapshotRecalcMode {
    /// Wipe all existing snapshots and recalculate from the earliest activity.
    Full,
    /// Resume from the latest existing snapshot, only computing new dates forward.
    IncrementalFromLast,
    /// Wipe snapshots from `date` forward and recalculate from that date,
    /// using the snapshot just before `date` as the initial state.
    SinceDate(NaiveDate),
}

// --- Service Trait ---
#[async_trait]
pub trait SnapshotServiceTrait: Send + Sync {
    /// Recalculates **holdings** snapshots for the given account IDs.
    /// The `mode` controls how much history is recomputed:
    /// - `Full`: wipe all snapshots and recalculate from the earliest activity.
    /// - `IncrementalFromLast`: resume from the latest existing snapshot.
    /// - `SinceDate(date)`: wipe from `date` forward and recalculate from that date.
    ///
    /// If `account_ids` is `None`, operates on all active accounts AND the "TOTAL" portfolio.
    /// Snapshots generated by this method *only contain holdings information* (quantities, costs, cash).
    async fn recalculate_holdings_snapshots(
        &self,
        account_ids: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize>;

    /// Retrieves calculated **holdings** keyframe snapshots for a specific
    /// account within a date range. Does NOT reconstruct daily snapshots;
    /// returns only the saved keyframes.
    fn get_holdings_keyframes(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>>;

    /// Retrieves **holdings** snapshots for a specific account within a date
    /// range, reconstructing daily snapshots between saved keyframes by
    /// carrying forward holdings. Valuation fields in the returned snapshots
    /// will be zero or default.
    fn get_daily_holdings_snapshots(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>>;

    /// Retrieves the most recent calculated **holdings** snapshot for a specific account.
    /// Returns `Ok(None)` when no snapshot exists yet. Valuation fields will be zero or default.
    fn get_latest_holdings_snapshot(
        &self,
        account_id: &str,
    ) -> Result<Option<AccountStateSnapshot>>;

    /// Returns cash balances by currency for the given account scope.
    ///
    /// For `PORTFOLIO_TOTAL_ACCOUNT_ID`, aggregates each non-archived account's
    /// latest snapshot `cash_balances` summed by currency (no merged TOTAL
    /// snapshot involved).
    ///
    /// For any other account id, returns the latest snapshot's `cash_balances`
    /// (empty map if no snapshot exists).
    fn get_cash_balances(&self, account_id: &str) -> Result<HashMap<String, Decimal>>;

    /// As-of-date variant of [`get_cash_balances`]. Uses the latest snapshot
    /// on or before `date` for each account.
    fn get_cash_balances_on_date(
        &self,
        account_id: &str,
        date: NaiveDate,
    ) -> Result<HashMap<String, Decimal>>;

    /// Saves a manual snapshot for the given account.
    /// - The snapshot's source is preserved from the input (e.g., ManualEntry or CsvImport).
    /// - If a snapshot exists for the same date, it is updated in place.
    /// - If the date is different from existing snapshots, a new snapshot is created.
    /// - Triggers valuation recalculation for the account after saving.
    async fn save_manual_snapshot(
        &self,
        account_id: &str,
        snapshot: AccountStateSnapshot,
    ) -> Result<()>;

    /// Updates the source field for all snapshots of an account.
    /// Used when switching tracking modes (e.g., from HOLDINGS to TRANSACTIONS).
    /// Returns the number of snapshots updated.
    async fn update_snapshots_source(&self, account_id: &str, new_source: &str) -> Result<usize>;

    /// Ensures HOLDINGS mode accounts have at least 2 snapshots for proper history.
    /// If only 1 non-calculated snapshot exists, creates a synthetic snapshot 3 months prior.
    /// This enables history charting, valuation engines, and provides an inception boundary.
    async fn ensure_holdings_history(&self, account_id: &str) -> Result<()>;

    /// After a manual snapshot is deleted, re-derives lots from the new latest snapshot
    /// (if it is MANUAL or IMPORTED) or clears the lots table for the account (if no
    /// snapshot remains). CALCULATED snapshots are ignored — those accounts have their
    /// lots managed by the transaction-replay pipeline.
    async fn refresh_lots_from_latest_snapshot(&self, account_id: &str) -> Result<()>;

    /// Populates the lots table for all HOLDINGS-mode accounts by deriving lots from
    /// each account's latest snapshot. Called during startup backfill because
    /// `recalculate_holdings_snapshots` only processes TRANSACTIONS-mode accounts.
    async fn backfill_lots_for_holdings_accounts(&self) -> Result<usize>;
}

// --- Service Implementation ---

#[derive(Clone)]
pub struct SnapshotService {
    #[allow(dead_code)]
    base_currency: Arc<RwLock<String>>,
    timezone: Arc<RwLock<String>>,
    account_repository: Arc<dyn AccountRepositoryTrait>,
    activity_repository: Arc<dyn ActivityRepositoryTrait>,
    snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
    lot_repository: Option<Arc<dyn LotRepositoryTrait>>,
    holdings_calculator: HoldingsCalculator,
    event_sink: Arc<dyn DomainEventSink>,
}

// Type aliases to simplify function signatures
type AccountsMap = HashMap<String, Account>; // Use HashMap for faster lookup
type ActivitiesVec = Vec<Activity>;
type ActivitiesByAccount = HashMap<String, BTreeMap<NaiveDate, Vec<Activity>>>;
type StartSnapshotsMap = HashMap<String, AccountStateSnapshot>;
type StartDatesMap = HashMap<String, NaiveDate>;

impl SnapshotService {
    pub fn new(
        base_currency: Arc<RwLock<String>>,
        account_repository: Arc<dyn AccountRepositoryTrait>,
        activity_repository: Arc<dyn ActivityRepositoryTrait>,
        snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
        asset_repository: Arc<dyn AssetRepositoryTrait>,
        fx_service: Arc<dyn FxServiceTrait>,
    ) -> Self {
        Self::new_with_timezone(
            base_currency,
            Arc::new(RwLock::new(String::new())),
            account_repository,
            activity_repository,
            snapshot_repository,
            asset_repository,
            fx_service,
        )
    }

    pub fn new_with_timezone(
        base_currency: Arc<RwLock<String>>,
        timezone: Arc<RwLock<String>>,
        account_repository: Arc<dyn AccountRepositoryTrait>,
        activity_repository: Arc<dyn ActivityRepositoryTrait>,
        snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
        asset_repository: Arc<dyn AssetRepositoryTrait>,
        fx_service: Arc<dyn FxServiceTrait>,
    ) -> Self {
        let holdings_calculator = HoldingsCalculator::new_with_timezone(
            fx_service.clone(),
            base_currency.clone(),
            timezone.clone(),
            asset_repository.clone(),
        );
        Self {
            base_currency: base_currency.clone(),
            timezone,
            account_repository,
            activity_repository,
            snapshot_repository,
            lot_repository: None,
            holdings_calculator,
            event_sink: Arc::new(NoOpDomainEventSink),
        }
    }

    fn user_date(&self, instant: chrono::DateTime<Utc>) -> NaiveDate {
        let tz = parse_user_timezone_or_default(&self.timezone.read().unwrap());
        activity_date_in_tz(instant, tz)
    }

    fn user_today(&self) -> NaiveDate {
        let tz = parse_user_timezone_or_default(&self.timezone.read().unwrap());
        user_today(tz)
    }

    /// Aggregates cash balances by walking the latest snapshot before
    /// `exclusive_upper` for the given account scope. For
    /// `PORTFOLIO_TOTAL_ACCOUNT_ID`, sums per-account cash by currency
    /// across all non-archived accounts. For any other account id, returns
    /// the latest snapshot's cash_balances (empty if none).
    fn aggregate_cash_for_scope(
        &self,
        account_id: &str,
        exclusive_upper: NaiveDate,
    ) -> Result<HashMap<String, Decimal>> {
        if account_id != PORTFOLIO_TOTAL_ACCOUNT_ID {
            return Ok(self
                .snapshot_repository
                .get_latest_snapshot_before_date(account_id, exclusive_upper)?
                .map(|s| s.cash_balances)
                .unwrap_or_default());
        }

        let non_archived = self.account_repository.list(None, Some(false), None)?;
        let mut totals: HashMap<String, Decimal> = HashMap::new();
        for account in non_archived {
            if account.id == PORTFOLIO_TOTAL_ACCOUNT_ID {
                continue;
            }
            let Some(snapshot) = self
                .snapshot_repository
                .get_latest_snapshot_before_date(&account.id, exclusive_upper)?
            else {
                continue;
            };
            for (currency, amount) in snapshot.cash_balances {
                *totals.entry(currency).or_insert(Decimal::ZERO) += amount;
            }
        }
        Ok(totals)
    }

    /// Sets the domain event sink for emitting HoldingsChanged events.
    pub fn with_event_sink(mut self, event_sink: Arc<dyn DomainEventSink>) -> Self {
        self.event_sink = event_sink;
        self
    }

    /// Attaches a lot repository so that lot rows are written alongside JSON
    /// snapshots on every recalculation. When set, the service writes lot rows
    /// for every non-TOTAL account after each holdings recalculation and logs
    /// any quantity mismatches at ERROR severity.
    pub fn with_lot_repository(mut self, lot_repository: Arc<dyn LotRepositoryTrait>) -> Self {
        self.lot_repository = Some(lot_repository);
        self
    }

    /// Emits a HoldingsChanged event for the given accounts and assets.
    fn emit_holdings_changed(&self, account_ids: Vec<String>, asset_ids: Vec<String>) {
        if !account_ids.is_empty() {
            self.event_sink.emit(DomainEvent::HoldingsChanged {
                account_ids,
                asset_ids,
            });
        }
    }


    // --- Core Calculation Logic (Internal Helper) ---
    async fn calculate_holdings_snapshots_internal(
        &self,
        account_ids_param: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize> {
        debug!(
            "Starting snapshot calculation (Holdings Only) for {:?} accounts. Mode: {:?}",
            account_ids_param, mode
        );

        let (accounts_to_process, all_activities, min_activity_date, calculation_end_date) =
            self.fetch_required_data(account_ids_param)?;

        if accounts_to_process.is_empty() {
            warn!("No accounts found to process.");
            return Ok(0);
        }

        if all_activities.is_empty() && matches!(mode, SnapshotRecalcMode::Full) {
            warn!("No activities found. Clearing snapshots due to Full recalc mode.");
            let ids_to_delete: Vec<String> = accounts_to_process.keys().cloned().collect();
            if !ids_to_delete.is_empty() {
                self.snapshot_repository
                    .delete_snapshots_by_account_ids(&ids_to_delete)
                    .await?;
            }
            return Ok(0);
        } else if all_activities.is_empty() {
            warn!("No activities found for accounts. Calculation will be trivial.");
            return Ok(0);
        }

        let (activities_by_account_date, account_ids_with_activity) = self.preprocess_data(
            &accounts_to_process,
            &all_activities,
            min_activity_date,
            calculation_end_date,
        )?;

        let (start_keyframes, effective_start_dates, calculation_min_date) = self
            .determine_calculation_range_and_initial_state(
                &accounts_to_process,
                &activities_by_account_date,
                &account_ids_with_activity,
                &mode,
                calculation_end_date,
            )
            .await?;

        let accounts_needing_calculation: AccountsMap = accounts_to_process
            .iter()
            .filter(|(id, _)| effective_start_dates.contains_key(*id))
            .map(|(id, acc)| (id.clone(), acc.clone()))
            .collect();

        if accounts_needing_calculation.is_empty() {
            debug!("No accounts require snapshot calculation in the specified range.");
            return Ok(0);
        }

        let (final_holdings_states, keyframes_to_save, calculation_warnings) = self
            .calculate_daily_holdings_snapshots(
                &accounts_needing_calculation,
                &activities_by_account_date,
                &start_keyframes,
                &effective_start_dates,
                calculation_min_date,
                calculation_end_date,
            )?;

        // Log detailed warnings for any activities that couldn't be processed
        if !calculation_warnings.is_empty() {
            error!(
                "Holdings snapshot calculation completed with {} activity warning(s):",
                calculation_warnings.len()
            );
            for warning in &calculation_warnings {
                error!("  - {}", warning);
            }
        }

        // Persist keyframe snapshots
        for acc_id in accounts_needing_calculation.keys() {
            let frames: Vec<_> = keyframes_to_save
                .iter()
                .filter(|kf| kf.account_id == *acc_id)
                .cloned()
                .collect();

            match &mode {
                SnapshotRecalcMode::Full => {
                    self.snapshot_repository
                        .overwrite_all_snapshots_for_account(acc_id, &frames)
                        .await?;
                }
                SnapshotRecalcMode::IncrementalFromLast | SnapshotRecalcMode::SinceDate(_) => {
                    let start = *effective_start_dates.get(acc_id).unwrap();
                    self.snapshot_repository
                        .overwrite_snapshots_for_account_in_range(
                            acc_id,
                            start,
                            calculation_end_date,
                            &frames,
                        )
                        .await?;
                }
            }
        }

        // Clean up stale snapshots and lots for accounts that were explicitly requested
        // but had no remaining activities (e.g., last activity deleted). These accounts
        // were skipped by determine_calculation_range_and_initial_state, so their
        // old snapshots and lots must be removed here.
        if let SnapshotRecalcMode::SinceDate(since) = &mode {
            for acc_id in accounts_to_process.keys() {
                if !accounts_needing_calculation.contains_key(acc_id) {
                    debug!(
                        "Cleaning up stale snapshots for account {} (no remaining activities)",
                        acc_id
                    );
                    self.snapshot_repository
                        .overwrite_snapshots_for_account_in_range(
                            acc_id,
                            *since,
                            calculation_end_date,
                            &[], // empty = delete old snapshots, insert nothing
                        )
                        .await?;

                    // Also clear lots — they were orphaned when activities were deleted
                    if let Some(lot_repo) = &self.lot_repository {
                        if let Err(e) = lot_repo.replace_lots_for_account(acc_id, &[]).await {
                            warn!(
                                "Failed to clear lots for account {} after activity deletion: {}",
                                acc_id, e
                            );
                        }
                    }
                }
            }
        }

        // Write lot rows alongside the JSON snapshots so both representations can
        // be compared during validation. Skips the virtual TOTAL account because it
        // has no activities of its own and its positions are derived at query time.
        //
        // For TRANSACTIONS-mode accounts, only sync lots during a Full recalc.
        // IncrementalFromLast and SinceDate modes load starting state from
        // snapshot positions JSON, which may contain stale lot quantities
        // (e.g. pre-split values from snapshots written before split adjustment
        // was implemented). The lots table is the source of truth for
        // TRANSACTIONS-mode accounts and should only be rewritten by a Full
        // recalc that replays all activities with proper split adjustment.
        if let Some(lot_repo) = &self.lot_repository {
            let is_full_recalc = matches!(mode, SnapshotRecalcMode::Full);
            for (acc_id, snapshot) in &final_holdings_states {
                // Skip lots sync for TRANSACTIONS accounts on non-Full recalcs
                if !is_full_recalc {
                    if let Some(account) = accounts_to_process.get(acc_id) {
                        if matches!(
                            account.tracking_mode,
                            crate::accounts::TrackingMode::Transactions
                                | crate::accounts::TrackingMode::NotSet
                        ) {
                            continue;
                        }
                    }
                }
                let open_lots = extract_lot_records(snapshot);
                let _ = check_lot_quantity_consistency(snapshot, &open_lots);
                let closures = self.holdings_calculator.take_disposed_lots(acc_id);
                if let Err(e) = lot_repo
                    .sync_lots_for_account(acc_id, &open_lots, &closures)
                    .await
                {
                    error!("Failed to sync lot rows for account {}: {}", acc_id, e);
                }
            }
        }

        Ok(keyframes_to_save.len())
    }

    // --- Step 1-3: Fetch required data ---
    // Fetches accounts based on `account_ids_param`. TOTAL ids are silently
    // ignored — TOTAL no longer has its own snapshots; the portfolio total is
    // synthesized on-demand by the valuation aggregator and the cash helper.
    fn fetch_required_data(
        &self,
        account_ids_param: Option<&[String]>,
    ) -> Result<(AccountsMap, ActivitiesVec, NaiveDate, NaiveDate)> {
        let mut accounts_to_process: AccountsMap = HashMap::new();
        let mut account_ids_to_fetch_activities: Vec<String> = Vec::new();

        // Collect individual accounts. Only TRANSACTIONS-mode accounts
        // participate in snapshot recalculation; HOLDINGS-mode accounts
        // manage their snapshots via manual entry/CSV import.
        match account_ids_param {
            Some(ids) => {
                // When specific account_ids are provided, process them regardless of is_active status
                // (per spec: "process exactly ids even inactive/archived for per-account rebuild")
                for id in ids {
                    if id == PORTFOLIO_TOTAL_ACCOUNT_ID {
                        continue;
                    }
                    if let Ok(acc) = self.account_repository.get_by_id(id) {
                        // Skip HOLDINGS mode accounts - they don't participate in transaction-based recalculation
                        if acc.tracking_mode == TrackingMode::Holdings {
                            debug!(
                                "Skipping account {} for snapshot recalculation: HOLDINGS tracking mode",
                                acc.id
                            );
                            continue;
                        }
                        account_ids_to_fetch_activities.push(acc.id.clone());
                        accounts_to_process.insert(acc.id.clone(), acc);
                    }
                }
            }
            None => {
                for acc in self.account_repository.list(Some(true), None, None)? {
                    // Skip HOLDINGS mode accounts - they don't participate in transaction-based recalculation
                    if acc.tracking_mode == TrackingMode::Holdings {
                        debug!(
                            "Skipping account {} for snapshot recalculation: HOLDINGS tracking mode",
                            acc.id
                        );
                        continue;
                    }
                    account_ids_to_fetch_activities.push(acc.id.clone());
                    accounts_to_process.insert(acc.id.clone(), acc);
                }
            }
        }

        // Pull activities for the collected individual accounts.
        let all_activities = if !account_ids_to_fetch_activities.is_empty() {
            self.activity_repository
                .get_activities_by_account_ids(&account_ids_to_fetch_activities)?
        } else {
            Vec::new()
        };

        // unchanged: compute min_activity_date & calculation_end_date …
        let min_activity_date = all_activities
            .iter()
            .map(|a| self.user_date(a.activity_date))
            .min()
            .unwrap_or_else(|| self.user_today());

        let calculation_end_date = self.user_today();

        Ok((
            accounts_to_process,
            all_activities,
            min_activity_date,
            calculation_end_date,
        ))
    }

    // --- Step 5: Preprocess activities ---
    // Compiles activities (expands DRIP, STAKING_REWARD, etc.), adjusts for splits, and groups.
    // If "TOTAL" account exists in `accounts_to_process`, adds ALL activities to its key.
    fn preprocess_data(
        &self,
        accounts_to_process: &AccountsMap, // Includes virtual TOTAL if needed
        all_activities: &[Activity],
        min_activity_date: NaiveDate,
        calculation_end_date: NaiveDate,
    ) -> Result<(ActivitiesByAccount, HashSet<String>)> {
        // First, compile activities to expand composite types (DRIP, STAKING_REWARD, DIVIDEND_IN_KIND)
        // into their constituent legs (e.g., INTEREST + BUY for staking rewards)
        let compiler = DefaultActivityCompiler::new();
        let compiled_activities = compiler.compile_all(all_activities)?;

        // Perform split adjustments on the compiled activity list
        let split_factors = self.calculate_split_factors(
            &compiled_activities,
            min_activity_date,
            calculation_end_date,
        );
        let adjusted_activities =
            self.adjust_activities_for_splits(&compiled_activities, &split_factors);

        // Group adjusted activities by original account ID and date
        let mut activities_by_account_date: ActivitiesByAccount = HashMap::new();
        let mut account_ids_with_activity: HashSet<String> = HashSet::new();

        for activity in &adjusted_activities {
            activities_by_account_date
                .entry(activity.account_id.clone())
                .or_default()
                .entry(self.user_date(activity.activity_date))
                .or_default()
                .push(activity.clone());
            account_ids_with_activity.insert(activity.account_id.clone());
        }

        // Ensure all accounts being processed (even those with no activities) have an entry
        // This simplifies downstream logic that expects keys to exist.
        for acc_id in accounts_to_process.keys() {
            activities_by_account_date
                .entry(acc_id.clone())
                .or_default();
        }

        Ok((activities_by_account_date, account_ids_with_activity))
    }

    // --- Step 6: Determine calculation range and initial state (Keyframes) ---
    // Handles individual accounts and the TOTAL account distinctly.
    async fn determine_calculation_range_and_initial_state(
        &self,
        accounts_to_process: &AccountsMap, // Includes virtual TOTAL if needed
        activities_by_account_date: &ActivitiesByAccount, // Includes TOTAL key if needed
        account_ids_with_activity: &HashSet<String>, // Accounts that actually have activities
        mode: &SnapshotRecalcMode,
        calculation_end_date: NaiveDate,
    ) -> Result<(StartSnapshotsMap, StartDatesMap, NaiveDate)> {
        debug!(
            "Determining calculation range. Accounts with activity: {:?}. Mode: {:?}",
            account_ids_with_activity.len(),
            mode
        );
        let mut start_keyframes: StartSnapshotsMap = HashMap::new();
        let mut effective_start_dates: StartDatesMap = HashMap::new();
        let mut overall_min_calc_date = calculation_end_date;

        for (acc_id, account) in accounts_to_process {
            if !account_ids_with_activity.contains(acc_id)
                && !matches!(mode, SnapshotRecalcMode::Full)
            {
                debug!("Skipping account {} for range determination: no activities and not forcing full.", acc_id);
                continue;
            }

            let min_activity_date_for_account = activities_by_account_date
                .get(acc_id)
                .and_then(|dates_map| dates_map.keys().next().cloned());

            let mut effective_start_date;
            let mut initial_snapshot_for_acc: Option<AccountStateSnapshot> = None;

            match mode {
                SnapshotRecalcMode::Full => {
                    effective_start_date =
                        min_activity_date_for_account.unwrap_or(calculation_end_date);
                    debug!(
                        "Full recalc: start_date for account {} = {}",
                        acc_id, effective_start_date
                    );
                }
                SnapshotRecalcMode::SinceDate(since) => {
                    // Use the snapshot strictly before `since` as the initial state,
                    // then recalculate forward from `since`.
                    // get_latest_snapshot_before_date is inclusive (<=), so subtract one day
                    // to avoid seeding from a keyframe on `since` itself, which would
                    // cause that day's activities to be applied twice.
                    let day_before_since = since.pred_opt().unwrap_or(*since);
                    if let Some(latest_snapshot) = self
                        .snapshot_repository
                        .get_latest_snapshot_before_date(acc_id, day_before_since)?
                    {
                        initial_snapshot_for_acc = Some(latest_snapshot);
                    }
                    effective_start_date = *since;
                    debug!(
                        "SinceDate recalc: start_date for account {} = {}",
                        acc_id, effective_start_date
                    );
                }
                SnapshotRecalcMode::IncrementalFromLast => {
                    if let Some(latest_snapshot) = self
                        .snapshot_repository
                        .get_latest_snapshot_before_date(acc_id, calculation_end_date)?
                    {
                        let snapshot_day = latest_snapshot.snapshot_date;
                        // Resume from the last known keyframe. The calculator expects the in-memory
                        // "previous" state to be the day before `effective_start_date`, so we start on
                        // the day *after* the stored keyframe to avoid re-processing that day’s activities.
                        initial_snapshot_for_acc = Some(latest_snapshot);
                        effective_start_date = snapshot_day.succ_opt().unwrap_or(snapshot_day);
                    } else {
                        effective_start_date =
                            min_activity_date_for_account.unwrap_or(calculation_end_date);
                        debug!(
                            "No snapshot found for account {}. Starting from earliest activity: {} or end_date.",
                            acc_id, effective_start_date
                        );
                    }

                    if let Some(min_act_date) = min_activity_date_for_account {
                        if initial_snapshot_for_acc.is_none() && min_act_date < effective_start_date
                        {
                            debug!(
                                "Account {} has activities (at {}) before determined start_date ({}). Adjusting to earliest activity.",
                                acc_id, min_act_date, effective_start_date
                            );
                            effective_start_date = min_act_date;
                            initial_snapshot_for_acc = None;
                        }
                    }
                }
            }

            if effective_start_date <= calculation_end_date {
                if let Some(snapshot) = initial_snapshot_for_acc {
                    start_keyframes.insert(acc_id.clone(), snapshot);
                } else {
                    let day_before_effective_start = effective_start_date
                        .pred_opt()
                        .unwrap_or(effective_start_date);
                    start_keyframes.insert(
                        acc_id.clone(),
                        Self::create_initial_snapshot(account, day_before_effective_start),
                    );
                }
                effective_start_dates.insert(acc_id.clone(), effective_start_date);
                if effective_start_date < overall_min_calc_date {
                    overall_min_calc_date = effective_start_date;
                }
            } else {
                debug!("Skipping account {} for calculation: effective_start_date {} is after calculation_end_date {}.",
                       acc_id, effective_start_date, calculation_end_date);
            }
        }

        if effective_start_dates.is_empty() && !accounts_to_process.is_empty() {
            warn!(
                "No effective calculation periods determined for any accounts. Min calc date defaults to end date: {}",
                calculation_end_date
            );
            overall_min_calc_date = calculation_end_date;
        } else if effective_start_dates.is_empty() && accounts_to_process.is_empty() {
            debug!(
                "No accounts to process, min calc date defaults to end date: {}",
                calculation_end_date
            );
            overall_min_calc_date = calculation_end_date;
        }

        Ok((
            start_keyframes,
            effective_start_dates,
            overall_min_calc_date,
        ))
    }

    // --- Step 7: Calculate daily holdings snapshots (in memory) and identify keyframes ---
    // Iterates through dates and calculates holdings for each account needing processing (incl. TOTAL).
    // Returns (final_states, keyframes, warnings) - warnings contain info about activities that couldn't be processed.
    #[allow(clippy::type_complexity)]
    fn calculate_daily_holdings_snapshots(
        &self,
        accounts_needing_calculation: &AccountsMap, // Actual accounts to process
        activities_by_account_date: &ActivitiesByAccount, // Includes TOTAL key if needed
        start_keyframes: &StartSnapshotsMap, // Initial states for accounts needing calculation
        effective_start_dates: &StartDatesMap, // Start dates for accounts needing calculation
        calculation_min_date: NaiveDate,
        calculation_end_date: NaiveDate,
    ) -> Result<(
        HashMap<String, AccountStateSnapshot>, // Final states
        Vec<AccountStateSnapshot>,             // Keyframes to save
        Vec<HoldingsCalculationWarning>,       // Warnings for activities that couldn't be processed
    )> {
        let mut current_holdings_snapshots = start_keyframes.clone();
        let mut keyframes_to_save: Vec<AccountStateSnapshot> = Vec::new();
        let mut all_warnings: Vec<HoldingsCalculationWarning> = Vec::new();
        let date_range = get_days_between(calculation_min_date, calculation_end_date);

        // Clear lot-level caches from any previous run
        self.holdings_calculator.clear_transfer_lots_cache();
        self.holdings_calculator.clear_disposed_lots();

        for current_date in date_range {
            // Process only accounts whose effective start date is today or earlier.
            // Order accounts so TRANSFER_OUT sources are processed before paired
            // TRANSFER_IN destinations (topological sort on source_group_id edges).
            let accounts_to_process_today = order_accounts_by_transfer_deps(
                accounts_needing_calculation,
                activities_by_account_date,
                effective_start_dates,
                current_date,
            );

            if accounts_to_process_today.is_empty() {
                // This shouldn't happen if calculation_min_date was determined correctly, but handle defensively.
                debug!(
                    "No accounts to process for date {}. Skipping day.",
                    current_date
                );
                continue;
            }

            let mut next_day_holdings_snapshots =
                HashMap::with_capacity(accounts_to_process_today.len());
            let mut keyframes_today = Vec::new();

            for (account_id, _account) in accounts_to_process_today {
                let previous_holdings_snapshot = current_holdings_snapshots
                    .get(account_id)
                     .ok_or_else(|| {
                         error!("CRITICAL: Missing previous holdings snapshot for account {} in memory map for date {}", account_id, current_date);
                         Error::Calculation(CalculatorError::Calculation(format!(
                             "Missing previous holdings snapshot for account {} for date {}",
                             account_id, current_date
                         )))
                     })?;

                // Get activities for THIS specific account (or the aggregated TOTAL activities)
                let activities_today = activities_by_account_date
                    .get(account_id) // Fetches individual or TOTAL activities based on account_id
                    .and_then(|date_map| date_map.get(&current_date))
                    .cloned()
                    .unwrap_or_default();

                let is_first_day = effective_start_dates.get(account_id) == Some(&current_date);
                let has_activities = !activities_today.is_empty();

                let current_holdings_snapshot: AccountStateSnapshot; // Final state for today

                if !has_activities {
                    // No activities today, just carry forward the previous state
                    let mut carried_forward_state = previous_holdings_snapshot.clone();
                    carried_forward_state.snapshot_date = current_date;
                    carried_forward_state.id =
                        format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                    // Note: calculated_at remains the same as the previous snapshot
                    current_holdings_snapshot = carried_forward_state;
                } else {
                    // Activities occurred, call the calculator
                    match self.holdings_calculator.calculate_next_holdings(
                        previous_holdings_snapshot,
                        &activities_today, // Pass the already fetched activities
                        current_date,
                    ) {
                        Ok(calc_result) => {
                            // Collect any warnings from activity processing
                            if calc_result.has_warnings() {
                                for warning in &calc_result.warnings {
                                    warn!(
                                        "Holdings calculation warning for account {} on {}: {}",
                                        account_id, current_date, warning
                                    );
                                }
                                all_warnings.extend(calc_result.warnings);
                            }

                            // Calculator provides the new state, including updated calculated_at
                            current_holdings_snapshot = calc_result.snapshot;

                            debug!(
                                "Holdings calculated successfully for account {} on {}",
                                account_id, current_date
                            );
                        }
                        Err(e) => {
                            error!(
                                "Holdings calculation failed for account {} on {}: {}. Carrying forward previous state.",
                                account_id, current_date, e
                            );
                            // Carry forward the previous day's state on error
                            let mut errored_state = previous_holdings_snapshot.clone();
                            errored_state.snapshot_date = current_date; // Update date even if carried forward
                            errored_state.id =
                                format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                            // calculated_at remains the same as the previous snapshot
                            current_holdings_snapshot = errored_state;
                        }
                    }
                }

                // Decide if it's a keyframe based on the determined snapshot
                // A keyframe is needed on the first day of calculation or if activities happened.
                let is_keyframe = is_first_day || has_activities;

                if is_keyframe {
                    // Create the keyframe based on the final state for today
                    let mut keyframe_snapshot = current_holdings_snapshot.clone();
                    // Ensure account_id and id are correctly set for the keyframe
                    keyframe_snapshot.account_id = account_id.clone();
                    keyframe_snapshot.id =
                        format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                    keyframes_today.push(keyframe_snapshot);
                }

                // Store the calculated/carried-forward snapshot for the next iteration's "previous" state
                next_day_holdings_snapshots
                    .insert(account_id.to_string(), current_holdings_snapshot); // Use the final determined snapshot
            }

            // Update the main state map for the next day
            // Important: Only update states for accounts processed today.
            for (id, state) in next_day_holdings_snapshots {
                current_holdings_snapshots.insert(id, state);
            }
            keyframes_to_save.extend(keyframes_today);
        }

        // Log summary of warnings if any occurred
        if !all_warnings.is_empty() {
            warn!(
                "Holdings calculation completed with {} warning(s) for activities that could not be processed",
                all_warnings.len()
            );
        }

        // Return the final holdings states, keyframes, and any warnings
        Ok((current_holdings_snapshots, keyframes_to_save, all_warnings))
    }


    // --- Helpers ---

    // create_initial_snapshot creates a snapshot with default values
    fn create_initial_snapshot(account: &Account, date: NaiveDate) -> AccountStateSnapshot {
        AccountStateSnapshot {
            id: AccountStateSnapshot::stable_id(&account.id, date),
            account_id: account.id.clone(),
            snapshot_date: date,
            currency: account.currency.clone(),
            positions: HashMap::new(),
            cash_balances: HashMap::new(),
            cost_basis: Decimal::ZERO,
            net_contribution: Decimal::ZERO,
            net_contribution_base: Decimal::ZERO,
            cash_total_account_currency: Decimal::ZERO,
            cash_total_base_currency: Decimal::ZERO,
            calculated_at: Utc::now().naive_utc(),
            source: SnapshotSource::Calculated,
        }
    }

    // (Helper function group_activities_by_account_and_date moved inside preprocess_data)

    fn calculate_split_factors(
        &self,
        activities: &[Activity],
        start_date: NaiveDate,
        end_date: NaiveDate,
    ) -> HashMap<String, Vec<(NaiveDate, Decimal)>> {
        use crate::activities::ACTIVITY_TYPE_SPLIT;
        let mut split_factors: HashMap<String, Vec<(NaiveDate, Decimal)>> = HashMap::new();
        for activity in activities.iter().filter(|a| {
            a.activity_type == ACTIVITY_TYPE_SPLIT
                && self.user_date(a.activity_date) >= start_date
                && self.user_date(a.activity_date) <= end_date
        }) {
            // Check if the activity amount exists and represents a valid positive split ratio
            let asset_id = match &activity.asset_id {
                Some(id) => id,
                None => {
                    warn!(
                        "Missing asset_id for Split activity {} on {}. Ignoring split.",
                        activity.id, activity.activity_date
                    );
                    continue;
                }
            };
            if let Some(split_ratio) = activity.amount {
                if split_ratio.is_sign_positive() && !split_ratio.is_zero() {
                    // Collect valid splits (date, ratio) for the asset
                    split_factors
                        .entry(asset_id.clone())
                        .or_default() // Get the Vec, create if needed
                        .push((self.user_date(activity.activity_date), split_ratio));
                // Push (date, ratio) tuple
                } else {
                    // Log warning for invalid ratio (e.g., zero or negative)
                    warn!(
                        "Invalid split ratio {} for Split activity {} on {}. Ignoring split.",
                        split_ratio, activity.id, activity.activity_date
                    );
                }
            } else {
                // Log warning if amount is missing for a split activity
                warn!(
                    "Missing amount for Split activity {} for asset {} on {}. Ignoring split.",
                    activity.id, asset_id, activity.activity_date
                );
            }
        }
        for splits in split_factors.values_mut() {
            splits.sort_by_key(|k| k.0);
            // Splits are stored per-account but are asset-level events; deduplicate by date
            // so that assets held in multiple accounts don't over-apply the same split.
            splits.dedup_by_key(|k| k.0);
        }
        split_factors
    }

    fn adjust_activities_for_splits(
        &self,
        activities: &[Activity],
        split_factors: &HashMap<String, Vec<(NaiveDate, Decimal)>>,
    ) -> Vec<Activity> {
        use crate::activities::ACTIVITY_TYPE_SPLIT;

        let mut adjusted_activities = Vec::with_capacity(activities.len());
        for activity in activities {
            let mut adj_activity = activity.clone();
            let asset_id = match &activity.asset_id {
                Some(id) => id,
                None => {
                    // No asset_id, just push the activity as-is
                    adjusted_activities.push(adj_activity);
                    continue;
                }
            };
            if let Some(splits) = split_factors.get(asset_id) {
                // Do not adjust the SPLIT activity itself, only others
                if adj_activity.activity_type != ACTIVITY_TYPE_SPLIT {
                    let mut cumulative_factor = Decimal::ONE;
                    // Apply splits that happened *after* the activity date
                    for (split_date, split_ratio) in splits.iter() {
                        // Iterate chronologically
                        if *split_date > self.user_date(activity.activity_date) {
                            // Split happened after this activity, need to adjust past quantity/price
                            cumulative_factor *= split_ratio;
                        }
                    }

                    if cumulative_factor != Decimal::ONE {
                        debug!(
                            "Adjusting activity {} on {} for asset {} due to future splits. Factor: {}",
                            adj_activity.id, self.user_date(activity.activity_date), asset_id, cumulative_factor
                        );
                        // Adjust quantity
                        // Use correct field name 'quantity'
                        adj_activity.quantity =
                            Some((activity.qty() * cumulative_factor).round_dp(DECIMAL_PRECISION));

                        // Adjust unit price (inverse factor)
                        // Use correct field name 'unit_price'
                        let unit_price = activity.price();
                        if !unit_price.is_zero() {
                            if !cumulative_factor.is_zero() {
                                // Avoid division by zero
                                // Use correct field name 'unit_price'
                                adj_activity.unit_price = Some(
                                    (unit_price / cumulative_factor).round_dp(DECIMAL_PRECISION),
                                );
                            } else {
                                warn!("Cumulative split factor is zero for activity {}. Cannot adjust unit price.", adj_activity.id);
                                // Use correct field name 'unit_price'
                                adj_activity.unit_price = Some(Decimal::ZERO); // Or handle as error?
                            }
                        }
                    }
                }
            }
            adjusted_activities.push(adj_activity);
        }
        adjusted_activities
    }

}

#[async_trait]
impl SnapshotServiceTrait for SnapshotService {
    async fn recalculate_holdings_snapshots(
        &self,
        account_ids: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize> {
        self.calculate_holdings_snapshots_internal(account_ids, mode)
            .await
    }

    fn get_holdings_keyframes(
        &self,
        account_id: &str,
        start_date_opt: Option<NaiveDate>,
        end_date_opt: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>> {
        debug!(
            "Getting saved holdings keyframes for {} from {:?} to {:?}",
            account_id, start_date_opt, end_date_opt
        );
        // Directly fetch from the repository without reconstruction
        self.snapshot_repository
            .get_snapshots_by_account(account_id, start_date_opt, end_date_opt)
    }

    fn get_daily_holdings_snapshots(
        &self,
        account_id: &str,
        start_date_opt: Option<NaiveDate>,
        end_date_opt: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>> {
        debug!(
            "Reconstructing daily holdings snapshots for {} from {:?} to {:?}",
            account_id, start_date_opt, end_date_opt
        );

        // Determine start date: Use provided, else earliest snapshot date
        let earliest_snapshot_date = self
            .snapshot_repository
            .get_earliest_snapshot_date(account_id)?;

        let start_date = match start_date_opt {
            Some(date) => date,
            None => match earliest_snapshot_date {
                Some(date) => date,
                None => {
                    debug!(
                        "No snapshots found for account {}. Returning empty.",
                        account_id
                    );
                    return Ok(Vec::new());
                }
            },
        };

        // Use provided end_date, or latest snapshot date, or today as fallback
        let end_date = match end_date_opt {
            Some(date) => date,
            None => {
                // Get the latest snapshot to ensure we include all available data
                // Use a far future date to get the absolute latest snapshot
                let today = self.user_today();
                let far_future = today + chrono::Duration::days(365);
                match self
                    .snapshot_repository
                    .get_latest_snapshot_before_date(account_id, far_future)?
                {
                    Some(latest_snapshot) => latest_snapshot.snapshot_date.max(today),
                    None => today,
                }
            }
        };

        if start_date > end_date {
            warn!(
                "get_daily_holdings_snapshots: Start date {} is after end date {}. Returning empty.",
                start_date, end_date
            );
            return Ok(Vec::new());
        }

        // Fetch keyframes within the actual range first, as we might need them to determine the initial state.
        let keyframes_in_range = self.snapshot_repository.get_snapshots_by_account(
            account_id,
            Some(start_date), // Fetch keyframes from start_date...
            Some(end_date),   // ...to end_date inclusive
        )?;
        let keyframes_map: BTreeMap<NaiveDate, AccountStateSnapshot> = keyframes_in_range
            .into_iter()
            .map(|kf| (kf.snapshot_date, kf))
            .collect();

        // Try to get the state from the day before the loop starts.
        let initial_state_result = self
            .snapshot_repository
            .get_latest_snapshot_before_date(account_id, start_date);

        let mut current_state = match initial_state_result? {
            Some(initial_snapshot) => initial_snapshot,
            None => {
                // No snapshot found before start date.
                // If there are no keyframes at all in the requested range, we can't reconstruct.
                if keyframes_map.is_empty() {
                    debug!("No snapshot found before start date {} and no keyframes in range for account {}. Returning empty.", start_date, account_id);
                    return Ok(Vec::new());
                }

                // Otherwise, history starts within our date range. We create a default "empty" state
                // for the day before the loop, and the loop will then pick up the first keyframe correctly.
                let account_details = self.account_repository.get_by_id(account_id)?;
                let day_before_start = start_date.pred_opt().unwrap_or(start_date);
                Self::create_initial_snapshot(&account_details, day_before_start)
            }
        };

        let capacity = (end_date - start_date).num_days().try_into().unwrap_or(0) + 1;
        let mut reconstructed_snapshots = Vec::with_capacity(capacity);
        let date_range = get_days_between(start_date, end_date);

        for current_date in date_range {
            if let Some(saved_keyframe) = keyframes_map.get(&current_date) {
                // Use the saved keyframe for this date
                current_state = saved_keyframe.clone();
                reconstructed_snapshots.push(saved_keyframe.clone());
            } else {
                // Reconstruct by carrying forward the previous day's state
                let mut reconstructed = current_state.clone();
                reconstructed.snapshot_date = current_date;
                reconstructed.id = format!(
                    "{}_{}",
                    reconstructed.account_id,
                    current_date.format("%Y-%m-%d")
                );
                // Removed lines attempting to reset non-existent valuation fields
                reconstructed.calculated_at = Utc::now().naive_utc(); // Mark when it was reconstructed

                current_state = reconstructed.clone(); // Update state for the next day
                reconstructed_snapshots.push(reconstructed);
            }
        }

        Ok(reconstructed_snapshots)
    }

    fn get_latest_holdings_snapshot(
        &self,
        account_id: &str,
    ) -> Result<Option<AccountStateSnapshot>> {
        let today = self.user_today();
        // The date passed to get_latest_snapshot_before_date is exclusive, so use tomorrow to include today.
        let tomorrow = today.succ_opt().unwrap_or(today);
        match self
            .snapshot_repository
            .get_latest_snapshot_before_date(account_id, tomorrow)?
        {
            Some(snapshot) => Ok(Some(snapshot)),
            None => {
                // It's possible no snapshot exists yet, which is not necessarily an error,
                // but we should inform the caller.
                debug!(
                    "No snapshot found for account {} on or before {}",
                    account_id, today
                );
                Ok(None)
            }
        }
    }

    fn get_cash_balances(&self, account_id: &str) -> Result<HashMap<String, Decimal>> {
        let today = self.user_today();
        let tomorrow = today.succ_opt().unwrap_or(today);
        self.aggregate_cash_for_scope(account_id, tomorrow)
    }

    fn get_cash_balances_on_date(
        &self,
        account_id: &str,
        date: NaiveDate,
    ) -> Result<HashMap<String, Decimal>> {
        let exclusive_upper = date.succ_opt().unwrap_or(date);
        self.aggregate_cash_for_scope(account_id, exclusive_upper)
    }

    async fn save_manual_snapshot(
        &self,
        account_id: &str,
        mut snapshot: AccountStateSnapshot,
    ) -> Result<()> {
        // Ensure the snapshot has the correct account_id
        snapshot.account_id = account_id.to_string();

        // Note: snapshot.source is preserved from the caller (ManualEntry or CsvImport)

        // Generate the snapshot ID based on account_id and date
        snapshot.id = AccountStateSnapshot::stable_id(account_id, snapshot.snapshot_date);

        // Check if content is unchanged from existing snapshot on the same date (skip if identical)
        // Only compare against the same date to avoid false matches with SYNTHETIC backfill snapshots
        let same_date_snapshots = self.snapshot_repository.get_snapshots_by_account(
            account_id,
            Some(snapshot.snapshot_date),
            Some(snapshot.snapshot_date),
        )?;

        if let Some(mut existing) = same_date_snapshots.into_iter().next() {
            // Enrich with positions from snapshot_positions table (DB load
            // no longer parses positions JSON).
            if existing.positions.is_empty() && existing.source.is_non_calculated() {
                existing.positions = self
                    .snapshot_repository
                    .get_snapshot_positions(&existing.id)?;
            }
            if existing.is_content_equal(&snapshot) {
                debug!(
                    "Snapshot content unchanged for account {} on {}, skipping save",
                    account_id, snapshot.snapshot_date
                );
                return Ok(());
            }
        }

        // Update the calculated_at timestamp
        snapshot.calculated_at = Utc::now().naive_utc();

        // Save or update the snapshot using repository method
        self.snapshot_repository
            .save_or_update_snapshot(&snapshot)
            .await?;

        info!(
            "Saved manual snapshot for account {} on date {}",
            account_id, snapshot.snapshot_date
        );

        // Write lots from the snapshot positions — but only if this is the latest snapshot
        // for the account (i.e. don't overwrite current open lots with stale historical data).
        if let Some(ref lot_repo) = self.lot_repository {
            let later_snapshots = self
                .snapshot_repository
                .get_snapshots_by_account(account_id, snapshot.snapshot_date.succ_opt(), None)
                .unwrap_or_default();
            let is_latest = later_snapshots.is_empty();

            if is_latest {
                let now = Utc::now().format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string();
                let open_date = snapshot.snapshot_date.format("%Y-%m-%d").to_string();
                let lot_records: Vec<LotRecord> = snapshot
                    .positions
                    .values()
                    .filter(|p| p.quantity > Decimal::ZERO)
                    .map(|p| LotRecord {
                        id: format!("HOLDINGS-{}-{}", account_id, p.asset_id),
                        account_id: account_id.to_string(),
                        asset_id: p.asset_id.clone(),
                        open_date: open_date.clone(),
                        open_activity_id: None,
                        original_quantity: p.quantity.to_string(),
                        remaining_quantity: p.quantity.to_string(),
                        cost_per_unit: p.average_cost.to_string(),
                        total_cost_basis: p.total_cost_basis.to_string(),
                        fee_allocated: "0".to_string(),
                        disposal_method: DisposalMethod::Fifo,
                        is_closed: false,
                        close_date: None,
                        close_activity_id: None,
                        is_wash_sale: false,
                        holding_period: None,
                        created_at: now.clone(),
                        updated_at: now.clone(),
                    })
                    .collect();

                if let Err(e) = lot_repo
                    .replace_lots_for_account(account_id, &lot_records)
                    .await
                {
                    warn!(
                        "Failed to write lots for HOLDINGS account {} from manual snapshot: {}",
                        account_id, e
                    );
                } else {
                    info!(
                        "Wrote {} lot(s) for HOLDINGS account {} from snapshot on {}",
                        lot_records.len(),
                        account_id,
                        snapshot.snapshot_date
                    );
                }
            }
        }

        // Emit HoldingsChanged event after successful save
        let asset_ids: Vec<String> = snapshot
            .positions
            .values()
            .map(|p| p.asset_id.clone())
            .collect();
        self.emit_holdings_changed(vec![account_id.to_string()], asset_ids);

        // Ensure holdings history has at least 2 snapshots
        self.ensure_holdings_history(account_id).await?;

        Ok(())
    }

    async fn refresh_lots_from_latest_snapshot(&self, account_id: &str) -> Result<()> {
        let lot_repo = match &self.lot_repository {
            Some(r) => r,
            None => return Ok(()),
        };

        let latest = self.get_latest_holdings_snapshot(account_id)?;

        match latest {
            None => {
                // No snapshot left — clear lots for this account.
                if let Err(e) = lot_repo.replace_lots_for_account(account_id, &[]).await {
                    warn!(
                        "Failed to clear lots for account {} after snapshot delete: {}",
                        account_id, e
                    );
                }
            }
            Some(snapshot)
                if matches!(
                    snapshot.source,
                    SnapshotSource::ManualEntry
                        | SnapshotSource::BrokerImported
                        | SnapshotSource::CsvImport
                        | SnapshotSource::Synthetic
                ) =>
            {
                // Load positions from snapshot_positions table
                let positions = self
                    .snapshot_repository
                    .get_snapshot_positions(&snapshot.id)?;

                let now = Utc::now().format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string();
                let open_date = snapshot.snapshot_date.format("%Y-%m-%d").to_string();
                let lot_records: Vec<LotRecord> = positions
                    .values()
                    .filter(|p| p.quantity > Decimal::ZERO)
                    .map(|p| LotRecord {
                        id: format!("HOLDINGS-{}-{}", account_id, p.asset_id),
                        account_id: account_id.to_string(),
                        asset_id: p.asset_id.clone(),
                        open_date: open_date.clone(),
                        open_activity_id: None,
                        original_quantity: p.quantity.to_string(),
                        remaining_quantity: p.quantity.to_string(),
                        cost_per_unit: p.average_cost.to_string(),
                        total_cost_basis: p.total_cost_basis.to_string(),
                        fee_allocated: "0".to_string(),
                        disposal_method: DisposalMethod::Fifo,
                        is_closed: false,
                        close_date: None,
                        close_activity_id: None,
                        is_wash_sale: false,
                        holding_period: None,
                        created_at: now.clone(),
                        updated_at: now.clone(),
                    })
                    .collect();

                if let Err(e) = lot_repo
                    .replace_lots_for_account(account_id, &lot_records)
                    .await
                {
                    warn!(
                        "Failed to refresh lots for account {} after snapshot delete: {}",
                        account_id, e
                    );
                } else {
                    info!(
                        "Refreshed {} lot(s) for account {} from new latest snapshot on {}",
                        lot_records.len(),
                        account_id,
                        snapshot.snapshot_date
                    );
                }
            }
            Some(_) => {
                // Latest snapshot is CALCULATED — lots are managed by the transaction-replay pipeline.
            }
        }

        Ok(())
    }

    async fn update_snapshots_source(&self, account_id: &str, new_source: &str) -> Result<usize> {
        debug!(
            "Updating snapshot source for account {} to {}",
            account_id, new_source
        );

        let updated_count = self
            .snapshot_repository
            .update_snapshots_source(account_id, new_source)
            .await?;

        info!(
            "Updated {} snapshots for account {} to source {}",
            updated_count, account_id, new_source
        );

        Ok(updated_count)
    }

    async fn ensure_holdings_history(&self, account_id: &str) -> Result<()> {
        // Get count of non-calculated snapshots
        let count = self
            .snapshot_repository
            .get_non_calculated_snapshot_count(account_id)?;

        if count >= 2 {
            debug!(
                "Account {} already has {} non-calculated snapshots, no synthetic needed",
                account_id, count
            );
            return Ok(());
        }

        if count == 0 {
            debug!(
                "Account {} has no non-calculated snapshots, nothing to backfill from",
                account_id
            );
            return Ok(());
        }

        // count == 1: Create synthetic snapshot 3 months before the earliest
        let earliest = self
            .snapshot_repository
            .get_earliest_non_calculated_snapshot(account_id)?;

        let mut earliest = match earliest {
            Some(s) => s,
            None => {
                debug!("No earliest snapshot found for account {}", account_id);
                return Ok(());
            }
        };

        // Enrich positions from snapshot_positions table (DB load no longer
        // parses positions JSON).
        if earliest.positions.is_empty() && earliest.source.is_non_calculated() {
            earliest.positions = self
                .snapshot_repository
                .get_snapshot_positions(&earliest.id)?;
        }

        // Calculate synthetic date: 3 months before earliest
        let synthetic_date = earliest
            .snapshot_date
            .checked_sub_months(Months::new(3))
            .unwrap_or(earliest.snapshot_date);

        // Don't create if synthetic date equals earliest (edge case)
        if synthetic_date == earliest.snapshot_date {
            debug!(
                "Synthetic date equals earliest date for account {}, skipping",
                account_id
            );
            return Ok(());
        }

        // Clone the earliest snapshot with new date and source
        let synthetic = AccountStateSnapshot {
            id: AccountStateSnapshot::stable_id(account_id, synthetic_date),
            account_id: account_id.to_string(),
            snapshot_date: synthetic_date,
            source: SnapshotSource::Synthetic,
            calculated_at: Utc::now().naive_utc(),
            // Clone all holdings data from earliest
            currency: earliest.currency,
            positions: earliest.positions,
            cash_balances: earliest.cash_balances,
            cost_basis: earliest.cost_basis,
            net_contribution: earliest.net_contribution,
            net_contribution_base: earliest.net_contribution_base,
            cash_total_account_currency: earliest.cash_total_account_currency,
            cash_total_base_currency: earliest.cash_total_base_currency,
        };

        self.snapshot_repository
            .save_or_update_snapshot(&synthetic)
            .await?;

        info!(
            "Created synthetic snapshot for account {} at {} (3 months before {})",
            account_id, synthetic_date, earliest.snapshot_date
        );

        Ok(())
    }

    async fn backfill_lots_for_holdings_accounts(&self) -> Result<usize> {
        let lot_repo = match &self.lot_repository {
            Some(r) => r,
            None => return Ok(0),
        };

        let accounts = self.account_repository.list(Some(true), None, None)?;
        let holdings_accounts: Vec<_> = accounts
            .into_iter()
            .filter(|a| a.tracking_mode == TrackingMode::Holdings)
            .collect();

        if holdings_accounts.is_empty() {
            return Ok(0);
        }

        let mut total_lots = 0usize;
        for acc in &holdings_accounts {
            match self.refresh_lots_from_latest_snapshot(&acc.id).await {
                Ok(()) => {
                    // Count lots written by checking what's now in the table for this account
                    match lot_repo.get_open_lots_for_account(&acc.id).await {
                        Ok(lots) => {
                            total_lots += lots.len();
                            if !lots.is_empty() {
                                info!(
                                    "Backfilled {} lot(s) for HOLDINGS account {}",
                                    lots.len(),
                                    acc.id
                                );
                            }
                        }
                        Err(e) => warn!(
                            "Could not count backfilled lots for account {}: {}",
                            acc.id, e
                        ),
                    }
                }
                Err(e) => warn!(
                    "Failed to backfill lots for HOLDINGS account {}: {}",
                    acc.id, e
                ),
            }
        }

        info!(
            "HOLDINGS lot backfill complete: {} lot(s) across {} account(s)",
            total_lots,
            holdings_accounts.len()
        );
        Ok(total_lots)
    }
}

/// Orders accounts for a given day so that TRANSFER_OUT sources are processed
/// before their paired TRANSFER_IN destinations. Uses topological sort (Kahn's
/// algorithm) on edges derived from `source_group_id` to handle chains (A→B→C).
/// Accounts without transfer dependencies retain their original order.
fn order_accounts_by_transfer_deps<'a>(
    accounts: &'a AccountsMap,
    activities_by_account_date: &ActivitiesByAccount,
    effective_start_dates: &StartDatesMap,
    current_date: NaiveDate,
) -> Vec<(&'a String, &'a Account)> {
    let eligible: Vec<(&String, &Account)> = accounts
        .iter()
        .filter(|(id, _)| {
            effective_start_dates
                .get(*id)
                .is_some_and(|start| *start <= current_date)
        })
        .collect();

    let n = eligible.len();
    if n <= 1 {
        return eligible;
    }

    // Map account_id → index
    let idx_of: HashMap<&str, usize> = eligible
        .iter()
        .enumerate()
        .map(|(i, (id, _))| (id.as_str(), i))
        .collect();

    // Scan today's activities to find source_group_id → (OUT account, IN account) pairs
    let mut out_idx_for_group: HashMap<String, usize> = HashMap::new();
    let mut in_idx_for_group: HashMap<String, usize> = HashMap::new();

    for (account_id, _) in &eligible {
        if let Some(activities) = activities_by_account_date
            .get(account_id.as_str())
            .and_then(|dates| dates.get(&current_date))
        {
            let acct_idx = idx_of[account_id.as_str()];
            for a in activities {
                if let Some(ref gid) = a.source_group_id {
                    if a.activity_type == "TRANSFER_OUT" {
                        out_idx_for_group.insert(gid.clone(), acct_idx);
                    } else if a.activity_type == "TRANSFER_IN" {
                        in_idx_for_group.insert(gid.clone(), acct_idx);
                    }
                }
            }
        }
    }

    // Build adjacency: out_account must be processed before in_account
    let mut successors: Vec<Vec<usize>> = vec![vec![]; n];
    let mut in_degree: Vec<u32> = vec![0; n];
    let mut has_edges = false;

    for (gid, &out_idx) in &out_idx_for_group {
        if let Some(&in_idx) = in_idx_for_group.get(gid) {
            if out_idx != in_idx {
                successors[out_idx].push(in_idx);
                in_degree[in_idx] += 1;
                has_edges = true;
            }
        }
    }

    if !has_edges {
        return eligible;
    }

    // Kahn's algorithm
    let mut queue: VecDeque<usize> = (0..n).filter(|&i| in_degree[i] == 0).collect();
    let mut order: Vec<usize> = Vec::with_capacity(n);

    while let Some(idx) = queue.pop_front() {
        order.push(idx);
        for &succ in &successors[idx] {
            in_degree[succ] -= 1;
            if in_degree[succ] == 0 {
                queue.push_back(succ);
            }
        }
    }

    // Append any remaining (would indicate a cycle — shouldn't happen in practice)
    if order.len() < n {
        let in_order: HashSet<usize> = order.iter().copied().collect();
        for i in 0..n {
            if !in_order.contains(&i) {
                order.push(i);
            }
        }
    }

    order.into_iter().map(|i| eligible[i]).collect()
}
