use super::holdings_calculator::{HoldingsCalculator, ProjectionRun};
use super::SnapshotRepositoryTrait;
use crate::accounts::{
    Account, AccountAccountingSettings, AccountRepositoryTrait, CostBasisMethod, TrackingMode,
};
use crate::activities::{
    Activity, ActivityCompiler, ActivityRepositoryTrait, DefaultActivityCompiler,
};
use crate::assets::AssetRepositoryTrait;
use crate::errors::{CalculatorError, Error, Result};
use crate::events::{DomainEvent, DomainEventSink, NoOpDomainEventSink};
use crate::fx::FxServiceTrait;
use crate::lots::{check_lot_quantity_consistency, LotRepositoryTrait};
use crate::portfolio::recalculation_gate::{
    PortfolioRecalculationGate, PortfolioRecalculationPermit,
};
use crate::portfolio::snapshot::{
    validate_snapshot_read_date, validate_snapshot_write_date, AccountStateSnapshot,
    HoldingsCalculationWarning, HoldingsTimeline, SnapshotMetadata, SnapshotSource,
};
use crate::utils::time_utils::{
    activity_date_in_tz, get_days_between, parse_user_timezone_or_default, user_today,
};

use async_trait::async_trait;
use chrono::{NaiveDate, Utc};
use log::{debug, error, info, warn};
use rust_decimal::Decimal;
use std::collections::{BTreeMap, HashMap, HashSet, VecDeque};
use std::sync::{Arc, RwLock};

// --- Recalculation mode ---

/// Controls the scope of a holdings snapshot recalculation.
#[derive(Clone, Debug)]
pub enum SnapshotRecalcMode {
    /// Wipe all existing snapshots and recalculate from the earliest activity.
    Full,
    /// Resume from the latest existing snapshot, only computing new dates forward.
    IncrementalFromLast,
    /// Wipe snapshots from `date` forward and recalculate from that date,
    /// using the snapshot just before `date` as the initial state.
    SinceDate(NaiveDate),
}

// --- Service Trait ---
#[async_trait]
pub trait SnapshotServiceTrait: Send + Sync {
    /// Recalculates **holdings** snapshots for the given account IDs.
    /// The `mode` controls how much history is recomputed:
    /// - `Full`: wipe all snapshots and recalculate from the earliest activity.
    /// - `IncrementalFromLast`: resume from the latest existing snapshot.
    /// - `SinceDate(date)`: wipe from `date` forward and recalculate from that date.
    ///
    /// If `account_ids` is `None`, operates on all active accounts.
    /// Snapshots generated by this method *only contain holdings information* (quantities, costs, cash).
    async fn recalculate_holdings_snapshots(
        &self,
        account_ids: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize>;

    /// Retrieves calculated **holdings** keyframe snapshots for a specific real account within a date range.
    /// Does NOT reconstruct daily snapshots; returns only the saved keyframes.
    fn get_holdings_keyframes(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>>;

    /// Retrieves lightweight snapshot metadata, including malformed stored
    /// dates that cannot be represented by `AccountStateSnapshot`.
    fn get_snapshot_metadata(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<SnapshotMetadata>> {
        self.get_holdings_keyframes(account_id, start_date, end_date)
            .map(|snapshots| snapshots.iter().map(SnapshotMetadata::from).collect())
    }

    /// Builds a sparse holdings timeline whose day iterator borrows active keyframes.
    fn get_holdings_timeline(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<HoldingsTimeline>;

    /// Retrieves the most recent calculated **holdings** snapshot for a specific account.
    /// Returns `Ok(None)` when no snapshot exists yet. Valuation fields will be zero or default.
    fn get_latest_holdings_snapshot(
        &self,
        account_id: &str,
    ) -> Result<Option<AccountStateSnapshot>>;

    /// Saves a manual snapshot for the given account.
    /// - The snapshot's source is preserved from the input (e.g., ManualEntry or CsvImport).
    /// - If a snapshot exists for the same date, it is updated in place.
    /// - If the date is different from existing snapshots, a new snapshot is created.
    /// - Triggers valuation recalculation for the account after saving.
    async fn save_manual_snapshot(
        &self,
        account_id: &str,
        snapshot: AccountStateSnapshot,
    ) -> Result<()>;

    /// Updates the source field for all snapshots of an account.
    /// Used when switching tracking modes (e.g., from HOLDINGS to TRANSACTIONS).
    /// Returns the number of snapshots updated.
    async fn update_snapshots_source(&self, account_id: &str, new_source: &str) -> Result<usize>;

    /// Delete snapshot(s) on the given dates.
    /// Keep UI/API callers behind the snapshot service boundary even though
    /// deletion currently delegates directly to storage. Higher-level
    /// orchestration (valuation recalc, frontend events) stays with the caller.
    async fn delete_snapshot_for_account(
        &self,
        account_id: &str,
        dates: &[NaiveDate],
    ) -> Result<()>;

    /// Deletes one snapshot by row ID, including a row whose stored date is
    /// malformed and therefore cannot use the date-based API.
    async fn delete_snapshot_for_account_by_id(
        &self,
        account_id: &str,
        snapshot_id: &str,
    ) -> Result<()> {
        let metadata = self
            .get_snapshot_metadata(account_id, None, None)?
            .into_iter()
            .find(|snapshot| snapshot.id == snapshot_id)
            .ok_or_else(|| {
                Error::Repository(format!(
                    "Snapshot {snapshot_id} for account {account_id} was not found"
                ))
            })?;
        let date = NaiveDate::parse_from_str(&metadata.snapshot_date, "%Y-%m-%d")
            .map_err(|error| Error::Repository(error.to_string()))?;
        self.delete_snapshot_for_account(account_id, &[date]).await
    }
}

// --- Service Implementation ---

#[derive(Clone)]
pub struct SnapshotService {
    timezone: Arc<RwLock<String>>,
    account_repository: Arc<dyn AccountRepositoryTrait>,
    activity_repository: Arc<dyn ActivityRepositoryTrait>,
    snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
    holdings_calculator: HoldingsCalculator,
    event_sink: Arc<dyn DomainEventSink>,
    /// Optional handle to the lots table. When attached, every successful
    /// snapshot computation also dual-writes lot rows alongside the existing
    /// positions JSON. Reads of the lots table happen elsewhere (or not at
    /// all in this PR — this is groundwork, not a read-path switchover).
    lot_repository: Option<Arc<dyn LotRepositoryTrait>>,
    recalculation_gate: Option<Arc<PortfolioRecalculationGate>>,
}

// Type aliases to simplify function signatures
type AccountsMap = HashMap<String, Account>; // Use HashMap for faster lookup
type ActivitiesVec = Vec<Activity>;
type ActivitiesByAccount = HashMap<String, BTreeMap<NaiveDate, Vec<Activity>>>;
type StartSnapshotsMap = HashMap<String, AccountStateSnapshot>;
type StartDatesMap = HashMap<String, NaiveDate>;

impl SnapshotService {
    pub fn new(
        base_currency: Arc<RwLock<String>>,
        account_repository: Arc<dyn AccountRepositoryTrait>,
        activity_repository: Arc<dyn ActivityRepositoryTrait>,
        snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
        asset_repository: Arc<dyn AssetRepositoryTrait>,
        fx_service: Arc<dyn FxServiceTrait>,
    ) -> Self {
        Self::new_with_timezone(
            base_currency,
            Arc::new(RwLock::new(String::new())),
            account_repository,
            activity_repository,
            snapshot_repository,
            asset_repository,
            fx_service,
        )
    }

    pub fn new_with_timezone(
        base_currency: Arc<RwLock<String>>,
        timezone: Arc<RwLock<String>>,
        account_repository: Arc<dyn AccountRepositoryTrait>,
        activity_repository: Arc<dyn ActivityRepositoryTrait>,
        snapshot_repository: Arc<dyn SnapshotRepositoryTrait>,
        asset_repository: Arc<dyn AssetRepositoryTrait>,
        fx_service: Arc<dyn FxServiceTrait>,
    ) -> Self {
        let holdings_calculator = HoldingsCalculator::new_with_timezone(
            fx_service.clone(),
            base_currency.clone(),
            timezone.clone(),
            asset_repository.clone(),
        );
        Self {
            timezone,
            account_repository,
            activity_repository,
            snapshot_repository,
            holdings_calculator,
            event_sink: Arc::new(NoOpDomainEventSink),
            lot_repository: None,
            recalculation_gate: None,
        }
    }

    /// Attaches a lot repository so that every snapshot computation also
    /// writes lot rows. When unset, the lots table is not written by the
    /// snapshot pipeline.
    pub fn with_lot_repository(mut self, lot_repository: Arc<dyn LotRepositoryTrait>) -> Self {
        self.lot_repository = Some(lot_repository);
        self
    }

    pub fn with_recalculation_gate(
        mut self,
        recalculation_gate: Arc<PortfolioRecalculationGate>,
    ) -> Self {
        self.recalculation_gate = Some(recalculation_gate);
        self
    }

    fn user_date(&self, instant: chrono::DateTime<Utc>) -> NaiveDate {
        let tz = parse_user_timezone_or_default(&self.timezone.read().unwrap());
        activity_date_in_tz(instant, tz)
    }

    fn user_today(&self) -> NaiveDate {
        let tz = parse_user_timezone_or_default(&self.timezone.read().unwrap());
        user_today(tz)
    }

    /// Sets the domain event sink for emitting HoldingsChanged events.
    pub fn with_event_sink(mut self, event_sink: Arc<dyn DomainEventSink>) -> Self {
        self.event_sink = event_sink;
        self
    }

    /// Emits a HoldingsChanged event for the given accounts and assets.
    fn emit_holdings_changed(
        &self,
        account_ids: Vec<String>,
        asset_ids: Vec<String>,
        earliest_snapshot_date: NaiveDate,
    ) {
        if !account_ids.is_empty() {
            self.event_sink.emit(DomainEvent::HoldingsChanged {
                account_ids,
                asset_ids,
                earliest_snapshot_date,
            });
        }
    }

    fn ensure_no_lot_sync_errors(lot_sync_errors: &[String]) -> Result<()> {
        if lot_sync_errors.is_empty() {
            return Ok(());
        }

        Err(Error::Database(crate::errors::DatabaseError::QueryFailed(
            format!(
                "lot sync failed for {} account(s): {}",
                lot_sync_errors.len(),
                lot_sync_errors.join("; ")
            ),
        )))
    }

    fn affected_activity_ids_for_account(
        activities_by_account_date: &ActivitiesByAccount,
        account_id: &str,
        start_date: NaiveDate,
        end_date: NaiveDate,
    ) -> Vec<String> {
        activities_by_account_date
            .get(account_id)
            .map(|by_date| {
                by_date
                    .range(start_date..=end_date)
                    .flat_map(|(_, activities)| {
                        activities.iter().map(|activity| activity.id.clone())
                    })
                    .collect()
            })
            .unwrap_or_default()
    }

    async fn affected_disposal_activity_ids_for_account(
        lot_repository: &(dyn LotRepositoryTrait + Send + Sync),
        activities_by_account_date: &ActivitiesByAccount,
        account_id: &str,
        start_date: NaiveDate,
        end_date: NaiveDate,
    ) -> Vec<String> {
        let mut activity_ids = Self::affected_activity_ids_for_account(
            activities_by_account_date,
            account_id,
            start_date,
            end_date,
        );

        match lot_repository
            .get_lot_disposals_for_account(account_id)
            .await
        {
            Ok(existing_disposals) => {
                activity_ids.extend(existing_disposals.into_iter().filter_map(|disposal| {
                    let disposal_date =
                        NaiveDate::parse_from_str(&disposal.disposal_date, "%Y-%m-%d").ok()?;
                    (disposal_date >= start_date && disposal_date <= end_date)
                        .then_some(disposal.disposal_activity_id)
                }));
            }
            Err(err) => {
                warn!(
                    "Failed to inspect existing lot disposals for account {}: {}",
                    account_id, err
                );
            }
        }

        activity_ids.sort();
        activity_ids.dedup();
        activity_ids
    }

    fn accounting_method_for_account<'a>(
        accounting_settings: &'a HashMap<String, AccountAccountingSettings>,
        account_id: &str,
    ) -> &'a str {
        accounting_settings
            .get(account_id)
            .map(|settings| settings.cost_basis_method.as_str())
            .unwrap_or(CostBasisMethod::Fifo.as_str())
    }

    async fn clear_stale_account_state(
        &self,
        account_ids: &[String],
        start_date: NaiveDate,
        end_date: NaiveDate,
        lot_sync_errors: &mut Vec<String>,
    ) -> Result<()> {
        for acc_id in account_ids {
            debug!(
                "Cleaning up stale snapshots for account {} (no remaining activities)",
                acc_id
            );
            self.snapshot_repository
                .overwrite_snapshots_for_account_in_range(acc_id, start_date, end_date, &[])
                .await?;

            if let Some(lot_repo) = &self.lot_repository {
                if let Err(e) = lot_repo.replace_lots_for_account(acc_id, &[]).await {
                    error!(
                        "Failed to clear lots for account {} after activity deletion: {}",
                        acc_id, e
                    );
                    lot_sync_errors.push(format!("{}: {}", acc_id, e));
                }
                if let Err(e) = lot_repo
                    .sync_lot_disposals_for_account(acc_id, &[], &[], true)
                    .await
                {
                    error!(
                        "Failed to clear lot disposals for account {} after activity deletion: {}",
                        acc_id, e
                    );
                    lot_sync_errors.push(format!("{} disposals: {}", acc_id, e));
                }
            }
        }

        Ok(())
    }

    // --- Core Calculation Logic (Internal Helper) ---
    async fn calculate_holdings_snapshots_internal(
        &self,
        account_ids_param: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize> {
        debug!(
            "Starting snapshot calculation (Holdings Only) for {:?} accounts. Mode: {:?}",
            account_ids_param, mode
        );

        // Enter the shared gate before reading activities. Acquiring after
        // `fetch_required_data` would serialize the writes while still allowing
        // a queued recalculation to run from data fetched before the prior one
        // completed.
        let recalculation_permit: Option<PortfolioRecalculationPermit> =
            match &self.recalculation_gate {
                Some(gate) => {
                    // Only the gate needs the id list; skip the account
                    // listing entirely on gate-less deployments.
                    let gate_account_ids: Vec<String> = match account_ids_param {
                        Some(account_ids) => account_ids.to_vec(),
                        None => self
                            .account_repository
                            .list(None, Some(false), None)?
                            .into_iter()
                            .filter(|account| account.tracking_mode != TrackingMode::Holdings)
                            .map(|account| account.id)
                            .collect(),
                    };
                    Some(gate.acquire(&gate_account_ids).await)
                }
                None => None,
            };

        let (accounts_to_process, all_activities, min_activity_date, calculation_end_date) =
            self.fetch_required_data(account_ids_param)?;

        if accounts_to_process.is_empty() {
            warn!("No accounts found to process.");
            return Ok(0);
        }

        let mode = if recalculation_permit
            .as_ref()
            .is_some_and(PortfolioRecalculationPermit::force_full)
        {
            SnapshotRecalcMode::Full
        } else {
            mode
        };

        // Enforce the append-only seeding contract before any mode-dependent
        // logic runs. A `SinceDate` recalc resumes from the snapshot just
        // before `since` and (post-STEP-2) hydrates that seed's lots from the
        // current `lots` table. That table is the CURRENT lot book (the latest
        // calculated state), so reusing it as a seed is only valid when the
        // change is strictly append-only — i.e. `since` is chronologically
        // AFTER every touched account's high-water mark, in which case the seed
        // IS the high-water-mark snapshot. A backdated add/edit/delete (`since`
        // on/before the high-water mark) must rebuild from inception instead,
        // because the current lots are post-sell remaining quantities, not the
        // lot book as of a historical date. Upgrade to `Full` in that case
        // (safe default; also covers accounts with no calculated state yet).
        let since_date = match &mode {
            SnapshotRecalcMode::SinceDate(since) => Some(*since),
            _ => None,
        };
        let mode = match since_date {
            Some(since)
                if !self.since_date_is_append_only(
                    &accounts_to_process,
                    since,
                    calculation_end_date,
                )? =>
            {
                info!(
                    "Backdated recalc: SinceDate({}) is on/before the high-water mark for at least \
                     one touched account. Rebuilding from inception (Full) so no historical \
                     snapshot is seeded from the current lots table.",
                    since
                );
                SnapshotRecalcMode::Full
            }
            _ => mode,
        };

        let mut lot_sync_errors: Vec<String> = Vec::new();

        if all_activities.is_empty() && matches!(mode, SnapshotRecalcMode::Full) {
            warn!("No activities found. Clearing snapshots due to Full recalc mode.");
            let ids_to_delete: Vec<String> = accounts_to_process.keys().cloned().collect();
            if !ids_to_delete.is_empty() {
                self.snapshot_repository
                    .delete_snapshots_by_account_ids(&ids_to_delete)
                    .await?;
                // Clear lots for the same accounts. Without this, deleting
                // the last activity for an account leaves orphan lot rows
                // pointing at no remaining snapshot/activity state — the
                // exact stale-lots situation the dual-write contract aims
                // to prevent. Propagate the error: if we just deleted the
                // user's snapshots and can't keep lots in sync, the caller
                // must know.
                if let Some(lot_repo) = &self.lot_repository {
                    for acc_id in &ids_to_delete {
                        lot_repo.replace_lots_for_account(acc_id, &[]).await?;
                        lot_repo
                            .sync_lot_disposals_for_account(acc_id, &[], &[], true)
                            .await?;
                    }
                }
            }
            return Ok(0);
        } else if all_activities.is_empty() {
            if let SnapshotRecalcMode::SinceDate(since) = &mode {
                warn!(
                    "No activities found. Clearing stale snapshots from {} due to SinceDate recalc.",
                    since
                );
                let ids_to_cleanup: Vec<String> = accounts_to_process.keys().cloned().collect();
                self.clear_stale_account_state(
                    &ids_to_cleanup,
                    *since,
                    calculation_end_date,
                    &mut lot_sync_errors,
                )
                .await?;
                Self::ensure_no_lot_sync_errors(&lot_sync_errors)?;
                return Ok(0);
            }
            warn!("No activities found for accounts. Calculation will be trivial.");
            return Ok(0);
        }

        let (activities_by_account_date, account_ids_with_activity) = self.preprocess_data(
            &accounts_to_process,
            &all_activities,
            min_activity_date,
            calculation_end_date,
        )?;

        let (start_keyframes, effective_start_dates, calculation_min_date, mut range_failures) =
            self.determine_calculation_range_and_initial_state(
                &accounts_to_process,
                &activities_by_account_date,
                &account_ids_with_activity,
                &mode,
                calculation_end_date,
            )
            .await?;
        // `accounts_to_process` is a HashMap; make the surfaced failure stable
        // while Health Center independently reports every affected account.
        range_failures.sort_by(|left, right| right.0.cmp(&left.0));

        let accounts_needing_calculation: AccountsMap = accounts_to_process
            .iter()
            .filter(|(id, _)| effective_start_dates.contains_key(*id))
            .map(|(id, acc)| (id.clone(), acc.clone()))
            .collect();

        if accounts_needing_calculation.is_empty() {
            debug!("No accounts require snapshot calculation in the specified range.");
            if let Some((_, error)) = range_failures.pop() {
                return Err(error);
            }
            return Ok(0);
        }

        let account_ids_needing_calculation: Vec<String> =
            accounts_needing_calculation.keys().cloned().collect();
        let accounting_settings = self
            .account_repository
            .get_accounting_settings_by_account_ids(&account_ids_needing_calculation)?;
        for acc_id in &account_ids_needing_calculation {
            accounting_settings
                .get(acc_id)
                .cloned()
                .unwrap_or_else(|| AccountAccountingSettings::default_for_account(acc_id.clone()))
                .ensure_supported_for_calculation()?;
        }

        // Per-run projection state (transfer-lot cache, disposals, cost-basis
        // methods). Lives for the whole recalculation run — across accounts and
        // days — then is drained per account when persisting lots below.
        let mut projection_run = ProjectionRun::new();

        let (final_holdings_states, keyframes_to_save, calculation_warnings) = self
            .calculate_daily_holdings_snapshots(
                &mut projection_run,
                &accounts_needing_calculation,
                &accounting_settings,
                &activities_by_account_date,
                &start_keyframes,
                &effective_start_dates,
                calculation_min_date,
                calculation_end_date,
            )?;

        // Log detailed warnings for any activities that couldn't be processed
        if !calculation_warnings.is_empty() {
            error!(
                "Holdings snapshot calculation completed with {} activity warning(s):",
                calculation_warnings.len()
            );
            for warning in &calculation_warnings {
                error!("  - {}", warning);
            }
        }

        // Persist keyframe snapshots
        for acc_id in accounts_needing_calculation.keys() {
            let frames: Vec<_> = keyframes_to_save
                .iter()
                .filter(|kf| kf.account_id == *acc_id)
                .cloned()
                .collect();

            match &mode {
                SnapshotRecalcMode::Full => {
                    self.snapshot_repository
                        .overwrite_all_snapshots_for_account(acc_id, &frames)
                        .await?;
                }
                SnapshotRecalcMode::IncrementalFromLast | SnapshotRecalcMode::SinceDate(_) => {
                    let start = *effective_start_dates.get(acc_id).unwrap();
                    self.snapshot_repository
                        .overwrite_snapshots_for_account_in_range(
                            acc_id,
                            start,
                            calculation_end_date,
                            &frames,
                        )
                        .await?;
                }
            }

            // Dual-write lots alongside the JSON snapshots. Use the
            // calculator's final in-memory state rather than the saved
            // keyframes — keyframes are sparse (one per significant date)
            // and may not include today, but the final state always reflects
            // current open lots after replay.
            //
            // Runs for every mode (Full, IncrementalFromLast, SinceDate). An
            // earlier revision skipped incremental modes for TRANSACTIONS-mode
            // accounts to guard against pre-PR snapshots carrying baked-in
            // split quantities, but the lots migration clears CALCULATED
            // snapshots so the next normal portfolio update rebuilds from
            // activity history and writes lots with the new semantics. After
            // that, incremental modes seed from known-good snapshots and
            // produce correct lots. The skip was preventing the normal
            // activity-edit flow (planner emits SinceDate) from ever updating
            // lots.
            //
            // HOLDINGS-mode positions are exposed as aggregate AssetLotView
            // rows from latest snapshots, not persisted as synthetic tax lots.
            if let Some(lot_repo) = &self.lot_repository {
                if let Some(snapshot) = final_holdings_states.get(acc_id) {
                    let cost_basis_method =
                        Self::accounting_method_for_account(&accounting_settings, acc_id);
                    let open_lots = self
                        .holdings_calculator
                        .extract_lot_records_with_base(snapshot, cost_basis_method);
                    let _ = check_lot_quantity_consistency(snapshot, &open_lots);
                    let closures = projection_run.take_disposed_lots(acc_id, cost_basis_method);
                    let disposals = projection_run.take_lot_disposals(acc_id, cost_basis_method);
                    let is_full = matches!(mode, SnapshotRecalcMode::Full);
                    let affected_disposal_activity_ids = if is_full {
                        Vec::new()
                    } else {
                        Self::affected_disposal_activity_ids_for_account(
                            lot_repo.as_ref(),
                            &activities_by_account_date,
                            acc_id,
                            *effective_start_dates
                                .get(acc_id)
                                .unwrap_or(&calculation_min_date),
                            calculation_end_date,
                        )
                        .await
                    };

                    // Special case: a Full recalc that produced zero open
                    // lots, zero closures, AND zero positions is the
                    // calculator authoritatively telling us this account
                    // holds nothing. The account may still have activities
                    // (DEPOSIT / DIVIDEND / INTEREST only) but no
                    // lot-producing ones. Stale lots from a previous,
                    // since-deleted BUY would otherwise survive because
                    // `sync_lots_for_account` deliberately preserves
                    // existing rows on empty input (its safety against a
                    // failed mid-replay). Caller explicitly opts into the
                    // wipe with `replace_lots_for_account(&[])`.
                    //
                    // Limited to Full mode: incremental modes seed from a
                    // prior snapshot's positions and might legitimately
                    // produce no NEW lots while carrying historical ones —
                    // we can't tell stale from genuine in that case, so the
                    // safety stays.
                    let calculator_says_empty = open_lots.is_empty()
                        && closures.is_empty()
                        && snapshot.positions.is_empty();

                    let result = if is_full && calculator_says_empty {
                        lot_repo.replace_lots_for_account(acc_id, &[]).await
                    } else {
                        lot_repo
                            .sync_lots_for_account(acc_id, &open_lots, &closures)
                            .await
                    };
                    if let Err(e) = result {
                        error!("Failed to sync lot rows for account {}: {}", acc_id, e);
                        lot_sync_errors.push(format!("{}: {}", acc_id, e));
                    }
                    if let Err(e) = lot_repo
                        .sync_lot_disposals_for_account(
                            acc_id,
                            &affected_disposal_activity_ids,
                            &disposals,
                            is_full,
                        )
                        .await
                    {
                        error!(
                            "Failed to sync lot disposal rows for account {}: {}",
                            acc_id, e
                        );
                        lot_sync_errors.push(format!("{} disposals: {}", acc_id, e));
                    }
                }
            }
        }

        // Clean up stale snapshots for accounts that were explicitly requested but
        // had no remaining activities (e.g., last activity deleted). These accounts
        // were skipped by determine_calculation_range_and_initial_state, so their
        // old snapshots must be removed here.
        if let SnapshotRecalcMode::SinceDate(since) = &mode {
            let failed_account_ids: HashSet<_> = range_failures
                .iter()
                .map(|(account_id, _)| account_id.as_str())
                .collect();
            let stale_account_ids: Vec<String> = accounts_to_process
                .keys()
                .filter(|acc_id| !accounts_needing_calculation.contains_key(*acc_id))
                .filter(|acc_id| !failed_account_ids.contains(acc_id.as_str()))
                .cloned()
                .collect();
            self.clear_stale_account_state(
                &stale_account_ids,
                *since,
                calculation_end_date,
                &mut lot_sync_errors,
            )
            .await?;
        }

        // Surface any per-account lot-sync failures collected during the
        // loop. Snapshots for the affected accounts WERE saved (the
        // snapshot write happens via `?` before the lot sync), but the
        // lots table diverged. Returning Err signals the caller that the
        // dual-write contract was partially broken and a retry / Full
        // recalc is needed to bring things back in sync.
        Self::ensure_no_lot_sync_errors(&lot_sync_errors)?;

        if let Some((_, error)) = range_failures.pop() {
            return Err(error);
        }

        Ok(keyframes_to_save.len())
    }

    // --- Step 1-3: Fetch required data ---
    // Fetches real accounts based on `account_ids_param`.
    // Fetches activities ONLY for the relevant accounts (specified or all).
    fn fetch_required_data(
        &self,
        account_ids_param: Option<&[String]>,
    ) -> Result<(AccountsMap, ActivitiesVec, NaiveDate, NaiveDate)> {
        let mut accounts_to_process: AccountsMap = HashMap::new();
        let mut account_ids_to_fetch_activities: Vec<String> = Vec::new();

        // ── ❶ collect real accounts ─────────────────────────────────────────────────
        // Only include TRANSACTIONS mode accounts for snapshot recalculation.
        // HOLDINGS mode accounts manage their snapshots via manual entry/CSV import.
        match account_ids_param {
            Some(ids) => {
                // When specific account_ids are provided, process them regardless of is_active status
                // (per spec: "process exactly ids even inactive/archived for per-account rebuild")
                for id in ids {
                    if let Ok(acc) = self.account_repository.get_by_id(id) {
                        // Skip HOLDINGS mode accounts - they don't participate in transaction-based recalculation
                        if acc.tracking_mode == TrackingMode::Holdings {
                            debug!(
                                "Skipping account {} for snapshot recalculation: HOLDINGS tracking mode",
                                acc.id
                            );
                            continue;
                        }
                        account_ids_to_fetch_activities.push(acc.id.clone());
                        accounts_to_process.insert(acc.id.clone(), acc);
                    }
                }
            }
            None => {
                for acc in self.account_repository.list(None, Some(false), None)? {
                    // Skip HOLDINGS mode accounts - they don't participate in transaction-based recalculation
                    if acc.tracking_mode == TrackingMode::Holdings {
                        debug!(
                            "Skipping account {} for snapshot recalculation: HOLDINGS tracking mode",
                            acc.id
                        );
                        continue;
                    }
                    account_ids_to_fetch_activities.push(acc.id.clone());
                    accounts_to_process.insert(acc.id.clone(), acc);
                }
            }
        }

        // ── ❷ pull activities for the collected individual accounts ──────────────────
        let all_activities = if !account_ids_to_fetch_activities.is_empty() {
            self.activity_repository
                .get_activities_by_account_ids(&account_ids_to_fetch_activities)?
        } else {
            Vec::new()
        };

        // unchanged: compute min_activity_date & calculation_end_date …
        let min_activity_date = all_activities
            .iter()
            .map(|a| self.user_date(a.activity_date))
            .min()
            .unwrap_or_else(|| self.user_today());

        let calculation_end_date = self.user_today();

        Ok((
            accounts_to_process,
            all_activities,
            min_activity_date,
            calculation_end_date,
        ))
    }

    // --- Step 5: Preprocess activities ---
    // Compiles activities (expands DRIP, STAKING_REWARD, etc.) and groups them
    // by account/date.
    //
    // Note: this used to also pre-adjust historical BUY/SELL quantities and
    // prices for subsequent SPLIT activities (so the calculator would see
    // post-split units everywhere). Splits are now tracked per-lot via the
    // `split_ratio` field — see `positions_model::Position::apply_split`. The
    // calculator iterates activities in chronological order and the SPLIT
    // handler multiplies each lot's stored ratio, leaving as-acquired
    // `quantity` / `acquisition_price` / `cost_basis` immutable. Pre-adjusting
    // here on top of the per-lot ratio would double-apply splits.
    fn preprocess_data(
        &self,
        accounts_to_process: &AccountsMap,
        all_activities: &[Activity],
        _min_activity_date: NaiveDate,
        _calculation_end_date: NaiveDate,
    ) -> Result<(ActivitiesByAccount, HashSet<String>)> {
        // First, compile activities to expand composite types (DRIP, STAKING_REWARD, DIVIDEND_IN_KIND)
        // into their constituent legs (e.g., INTEREST + BUY for staking rewards)
        let compiler = DefaultActivityCompiler::new();
        let compiled_activities = compiler.compile_all(all_activities)?;

        // Group activities by original account ID and date. Splits are now
        // tracked per-lot via split_ratio, so no pre-adjustment is needed.
        let mut activities_by_account_date: ActivitiesByAccount = HashMap::new();
        let mut account_ids_with_activity: HashSet<String> = HashSet::new();

        for activity in &compiled_activities {
            activities_by_account_date
                .entry(activity.account_id.clone())
                .or_default()
                .entry(self.user_date(activity.activity_date))
                .or_default()
                .push(activity.clone());
            account_ids_with_activity.insert(activity.account_id.clone());
        }

        // Ensure all accounts being processed (even those with no activities) have an entry
        // This simplifies downstream logic that expects keys to exist.
        for acc_id in accounts_to_process.keys() {
            activities_by_account_date
                .entry(acc_id.clone())
                .or_default();
        }

        Ok((activities_by_account_date, account_ids_with_activity))
    }

    /// Decides whether a `SinceDate(since)` recalc is strictly *append-only*
    /// for every account it will touch.
    ///
    /// An account's **high-water mark** is its latest calculated snapshot date
    /// (`get_latest_snapshot_before_date(acc, calculation_end_date)` — the same
    /// accessor `IncrementalFromLast` uses to find the resume point). The
    /// `lots` table holds the CURRENT lot book keyed to that high-water mark,
    /// so seeding a recalc from it is only valid when the earliest changed
    /// activity lands chronologically AFTER the high-water mark: then the
    /// seed snapshot (the one just before `since`) *is* the high-water-mark
    /// snapshot and its hydrated lots match the table.
    ///
    /// Returns `false` (the caller upgrades the run to `Full`, rebuilding from
    /// inception) when ANY touched account has `since <= high_water_mark`
    /// (a backdated add/edit/delete) or has no calculated snapshot yet. Failing
    /// closed to `Full` is always safe.
    fn since_date_is_append_only(
        &self,
        accounts_to_process: &AccountsMap,
        since: NaiveDate,
        calculation_end_date: NaiveDate,
    ) -> Result<bool> {
        for acc_id in accounts_to_process.keys() {
            let high_water_mark = self
                .snapshot_repository
                .get_latest_snapshot_before_date(acc_id, calculation_end_date)?
                .map(|snapshot| snapshot.snapshot_date);
            match high_water_mark {
                // Strictly after the latest calculated state → append-only for
                // this account.
                Some(hwm) if since > hwm => {}
                // On/before the high-water mark (backdated), or no calculated
                // state yet → must rebuild from inception.
                _ => return Ok(false),
            }
        }
        Ok(true)
    }

    // --- Step 6: Determine calculation range and initial state (Keyframes) ---
    // Handles real accounts.
    async fn determine_calculation_range_and_initial_state(
        &self,
        accounts_to_process: &AccountsMap,
        activities_by_account_date: &ActivitiesByAccount,
        account_ids_with_activity: &HashSet<String>, // Accounts that actually have activities
        mode: &SnapshotRecalcMode,
        calculation_end_date: NaiveDate,
    ) -> Result<(
        StartSnapshotsMap,
        StartDatesMap,
        NaiveDate,
        Vec<(String, Error)>,
    )> {
        debug!(
            "Determining calculation range. Accounts with activity: {:?}. Mode: {:?}",
            account_ids_with_activity.len(),
            mode
        );
        let mut start_keyframes: StartSnapshotsMap = HashMap::new();
        let mut effective_start_dates: StartDatesMap = HashMap::new();
        let mut overall_min_calc_date = calculation_end_date;
        let mut range_failures = Vec::new();

        for (acc_id, account) in accounts_to_process {
            if !account_ids_with_activity.contains(acc_id)
                && !matches!(mode, SnapshotRecalcMode::Full)
            {
                debug!(
                    "Skipping account {} for range determination: no activities and not forcing full.",
                    acc_id
                );
                continue;
            }

            let min_activity_date_for_account = activities_by_account_date
                .get(acc_id)
                .and_then(|dates_map| dates_map.keys().next().cloned());

            let mut effective_start_date;
            let mut initial_snapshot_for_acc: Option<AccountStateSnapshot> = None;

            match mode {
                SnapshotRecalcMode::Full => {
                    effective_start_date =
                        min_activity_date_for_account.unwrap_or(calculation_end_date);
                    debug!(
                        "Full recalc: start_date for account {} = {}",
                        acc_id, effective_start_date
                    );
                }
                SnapshotRecalcMode::SinceDate(since) => {
                    // Invariant: by the time a `SinceDate` reaches here it is
                    // strictly append-only — `calculate_holdings_snapshots_internal`
                    // upgrades any backdated `SinceDate` (`since` on/before an
                    // account's high-water mark) to `Full`. So `since` is after
                    // every touched account's high-water mark, which means the
                    // snapshot located below is that high-water-mark snapshot
                    // (the latest calculated state). Seeding from it — and
                    // hydrating its lots from the current `lots` table — is
                    // therefore valid.
                    //
                    // Use the snapshot strictly before `since` as the initial state,
                    // then recalculate forward from `since`.
                    // get_latest_snapshot_before_date is inclusive (<=), so subtract one day
                    // to avoid seeding from a keyframe on `since` itself, which would
                    // cause that day's activities to be applied twice.
                    let day_before_since = since.pred_opt().unwrap_or(*since);
                    if let Some(latest_snapshot) = self
                        .snapshot_repository
                        .get_latest_snapshot_before_date(acc_id, day_before_since)?
                    {
                        initial_snapshot_for_acc = Some(latest_snapshot);
                    }
                    effective_start_date = *since;
                    debug!(
                        "SinceDate recalc: start_date for account {} = {}",
                        acc_id, effective_start_date
                    );
                }
                SnapshotRecalcMode::IncrementalFromLast => {
                    if let Some(latest_snapshot) = self
                        .snapshot_repository
                        .get_latest_snapshot_before_date(acc_id, calculation_end_date)?
                    {
                        let snapshot_day = latest_snapshot.snapshot_date;
                        // Resume from the last known keyframe. The calculator expects the in-memory
                        // "previous" state to be the day before `effective_start_date`, so we start on
                        // the day *after* the stored keyframe to avoid re-processing that day’s activities.
                        initial_snapshot_for_acc = Some(latest_snapshot);
                        effective_start_date = snapshot_day.succ_opt().unwrap_or(snapshot_day);
                    } else {
                        effective_start_date =
                            min_activity_date_for_account.unwrap_or(calculation_end_date);
                        debug!(
                            "No snapshot found for account {}. Starting from earliest activity: {} or end_date.",
                            acc_id, effective_start_date
                        );
                    }

                    if let Some(min_act_date) = min_activity_date_for_account {
                        if initial_snapshot_for_acc.is_none() && min_act_date < effective_start_date
                        {
                            debug!(
                                "Account {} has activities (at {}) before determined start_date ({}). Adjusting to earliest activity.",
                                acc_id, min_act_date, effective_start_date
                            );
                            effective_start_date = min_act_date;
                            initial_snapshot_for_acc = None;
                        }
                    }
                }
            }

            if initial_snapshot_for_acc.is_some() {
                if let (Some(min_activity_date), Some(split_date)) = (
                    min_activity_date_for_account,
                    Self::first_split_date_in_range(
                        activities_by_account_date,
                        acc_id,
                        effective_start_date,
                        calculation_end_date,
                    ),
                ) {
                    if min_activity_date < effective_start_date {
                        debug!(
                            "Account {} has split activity on {} inside recalculation window. Restarting from earliest activity {} so historical lots are split-adjusted.",
                            acc_id, split_date, min_activity_date
                        );
                        effective_start_date = min_activity_date;
                        initial_snapshot_for_acc = None;
                    }
                }
            }

            if effective_start_date <= calculation_end_date {
                // Activity dates and planner-provided SinceDate values can come
                // from existing or synced data, bypassing snapshot write checks.
                // Bound the effective range before get_days_between allocates it.
                if let Err(error) = validate_snapshot_read_date(
                    acc_id,
                    effective_start_date,
                    SnapshotSource::Calculated.as_str(),
                    calculation_end_date,
                ) {
                    warn!(
                        "Skipping snapshot recalculation for account {} because its effective start date is invalid: {}",
                        acc_id, error
                    );
                    range_failures.push((acc_id.clone(), error));
                    continue;
                }
                if let Some(mut snapshot) = initial_snapshot_for_acc {
                    // A seed snapshot only reaches here for the append-only
                    // modes — `IncrementalFromLast` (resumes from the latest
                    // keyframe) or a `SinceDate` that survived the backdated →
                    // `Full` upgrade (so `since` is after the high-water mark,
                    // making this snapshot the latest calculated state). `Full`
                    // never populates `initial_snapshot_for_acc`. That makes it
                    // safe to hydrate the seed's lots from the current `lots`
                    // table (the source of truth for the latest calculated
                    // state): newly written snapshots omit embedded lots
                    // (STEP 2), so carried positions would otherwise seed with
                    // zero lots.
                    self.hydrate_seed_lots_from_table(&mut snapshot).await;
                    start_keyframes.insert(acc_id.clone(), snapshot);
                } else {
                    let day_before_effective_start = effective_start_date
                        .pred_opt()
                        .unwrap_or(effective_start_date);
                    start_keyframes.insert(
                        acc_id.clone(),
                        Self::create_initial_snapshot(account, day_before_effective_start),
                    );
                }
                effective_start_dates.insert(acc_id.clone(), effective_start_date);
                if effective_start_date < overall_min_calc_date {
                    overall_min_calc_date = effective_start_date;
                }
            } else {
                debug!(
                    "Skipping account {} for calculation: effective_start_date {} is after calculation_end_date {}.",
                    acc_id, effective_start_date, calculation_end_date
                );
            }
        }

        if effective_start_dates.is_empty() && !accounts_to_process.is_empty() {
            warn!(
                "No effective calculation periods determined for any accounts. Min calc date defaults to end date: {}",
                calculation_end_date
            );
            overall_min_calc_date = calculation_end_date;
        } else if effective_start_dates.is_empty() && accounts_to_process.is_empty() {
            debug!(
                "No accounts to process, min calc date defaults to end date: {}",
                calculation_end_date
            );
            overall_min_calc_date = calculation_end_date;
        }

        Ok((
            start_keyframes,
            effective_start_dates,
            overall_min_calc_date,
            range_failures,
        ))
    }

    /// Hydrates a seed snapshot's per-position `lots` from the normalized
    /// `lots` table (the source of truth) for positions whose embedded lots are
    /// empty.
    ///
    /// **Invariant: this only ever runs against an append-only seed** — the
    /// latest calculated state. Callers reach it only for `IncrementalFromLast`
    /// (resumes from the latest keyframe) or a `SinceDate` that survived the
    /// backdated → `Full` upgrade in `calculate_holdings_snapshots_internal`
    /// (so `since` is after the high-water mark and the seed IS the latest
    /// keyframe). Backdated `SinceDate` recalcs are rebuilt from inception as
    /// `Full` and never hydrate here, because the current `lots` table holds
    /// post-sell remaining quantities, not the lot book as of a historical
    /// date. Sourcing seed lots from the table would corrupt a historical seed.
    ///
    /// Given that invariant, sourcing seed lots from the table is correct: the
    /// table is the source of truth for the latest calculated state. STEP 2
    /// (`#[serde(skip_serializing)]` on `Position.lots`) means newly written
    /// snapshots omit embedded lots, so carried / out-of-window positions
    /// deserialize with zero lots. Replaying from that empty seed and
    /// extracting lots would (a) trip the `lots sum to 0` consistency check and
    /// (b) leave stale rows because `sync_lots_for_account` preserves existing
    /// rows on empty input. Hydrating from the table keeps the in-memory recalc
    /// and the table consistent.
    ///
    /// Positions that still carry embedded lots (pre-STEP-2 snapshots) are left
    /// untouched. A `Full` recalc never reaches here — it seeds from a freshly
    /// created empty snapshot and replays from inception. Repository absence or
    /// error is non-fatal: the seed keeps its embedded lots and the recalc
    /// proceeds as before.
    async fn hydrate_seed_lots_from_table(&self, snapshot: &mut AccountStateSnapshot) {
        let Some(lot_repository) = &self.lot_repository else {
            return;
        };

        // Only hydrate when at least one position is missing its lots; avoids a
        // query for fully-embedded (pre-STEP-2) seeds.
        if !snapshot.positions.values().any(|p| p.lots.is_empty()) {
            return;
        }

        let open_lots = match lot_repository
            .get_open_lots_for_account(&snapshot.account_id)
            .await
        {
            Ok(lots) => lots,
            Err(e) => {
                warn!(
                    "Failed to hydrate seed lots from lots table for account {}: {}. \
                     Proceeding with embedded snapshot lots.",
                    snapshot.account_id, e
                );
                return;
            }
        };

        if open_lots.is_empty() {
            return;
        }

        // Group open lot rows by asset so each position is filled in one pass.
        let mut lots_by_asset: HashMap<String, VecDeque<crate::portfolio::snapshot::Lot>> =
            HashMap::new();
        for record in open_lots {
            let asset_id = record.asset_id.clone();
            let position_id = snapshot
                .positions
                .get(&asset_id)
                .map(|p| p.id.clone())
                .unwrap_or_else(|| asset_id.clone());
            lots_by_asset.entry(asset_id).or_default().push_back(
                crate::lots::lot_record_to_snapshot_lot(&position_id, record),
            );
        }

        for (asset_id, position) in snapshot.positions.iter_mut() {
            if position.lots.is_empty() {
                if let Some(lots) = lots_by_asset.remove(asset_id) {
                    position.lots = lots;
                }
            }
        }
    }

    fn first_split_date_in_range(
        activities_by_account_date: &ActivitiesByAccount,
        account_id: &str,
        start_date: NaiveDate,
        end_date: NaiveDate,
    ) -> Option<NaiveDate> {
        use crate::activities::ACTIVITY_TYPE_SPLIT;

        if start_date > end_date {
            return None;
        }

        activities_by_account_date
            .get(account_id)?
            .range(start_date..=end_date)
            .find_map(|(date, activities)| {
                activities
                    .iter()
                    .any(|activity| activity.activity_type == ACTIVITY_TYPE_SPLIT)
                    .then_some(*date)
            })
    }

    // --- Step 7: Calculate daily holdings snapshots (in memory) and identify keyframes ---
    // Iterates through dates and calculates holdings for each real account needing processing.
    // Returns (final_states, keyframes, warnings) - warnings contain info about activities that couldn't be processed.
    #[allow(clippy::too_many_arguments, clippy::type_complexity)]
    fn calculate_daily_holdings_snapshots(
        &self,
        run: &mut ProjectionRun,
        accounts_needing_calculation: &AccountsMap, // Actual accounts to process
        accounting_settings: &HashMap<String, AccountAccountingSettings>,
        activities_by_account_date: &ActivitiesByAccount,
        start_keyframes: &StartSnapshotsMap, // Initial states for accounts needing calculation
        effective_start_dates: &StartDatesMap, // Start dates for accounts needing calculation
        calculation_min_date: NaiveDate,
        calculation_end_date: NaiveDate,
    ) -> Result<(
        HashMap<String, AccountStateSnapshot>, // Final states
        Vec<AccountStateSnapshot>,             // Keyframes to save
        Vec<HoldingsCalculationWarning>,       // Warnings for activities that couldn't be processed
    )> {
        let mut current_holdings_snapshots = start_keyframes.clone();
        let mut keyframes_to_save: Vec<AccountStateSnapshot> = Vec::new();
        let mut all_warnings: Vec<HoldingsCalculationWarning> = Vec::new();
        let date_range = get_days_between(calculation_min_date, calculation_end_date);

        // Register each account's cost-basis method for this run. The run was
        // created fresh by the caller, so there is no stale cache to clear.
        for account_id in accounts_needing_calculation.keys() {
            run.set_cost_basis_method(
                account_id,
                Self::accounting_method_for_account(accounting_settings, account_id),
            );
        }

        for current_date in date_range {
            // Process only accounts whose effective start date is today or earlier.
            // Order accounts so TRANSFER_OUT sources are processed before paired
            // TRANSFER_IN destinations (topological sort on source_group_id edges).
            let accounts_to_process_today = order_accounts_by_transfer_deps(
                accounts_needing_calculation,
                activities_by_account_date,
                effective_start_dates,
                current_date,
            );

            if accounts_to_process_today.is_empty() {
                // This shouldn't happen if calculation_min_date was determined correctly, but handle defensively.
                debug!(
                    "No accounts to process for date {}. Skipping day.",
                    current_date
                );
                continue;
            }

            let mut next_day_holdings_snapshots =
                HashMap::with_capacity(accounts_to_process_today.len());
            let mut keyframes_today = Vec::new();

            for (account_id, account) in accounts_to_process_today {
                // Get activities for this specific account.
                let activities_today = activities_by_account_date
                    .get(account_id)
                    .and_then(|date_map| date_map.get(&current_date))
                    .cloned()
                    .unwrap_or_default();

                let is_first_day = effective_start_dates.get(account_id) == Some(&current_date);
                let has_activities = !activities_today.is_empty();

                // Saved holdings are keyframes, so an empty calendar day does not
                // change the state and does not need a deep clone of positions/lots.
                if !is_first_day && !has_activities {
                    continue;
                }

                let previous_holdings_snapshot = current_holdings_snapshots
                    .get(account_id)
                     .ok_or_else(|| {
                         error!("CRITICAL: Missing previous holdings snapshot for account {} in memory map for date {}", account_id, current_date);
                         Error::Calculation(CalculatorError::Calculation(format!(
                             "Missing previous holdings snapshot for account {} for date {}",
                             account_id, current_date
                         )))
                     })?;

                let current_holdings_snapshot: AccountStateSnapshot; // Final state for today

                if !has_activities {
                    // No activities today, just carry forward the previous state
                    let mut carried_forward_state = previous_holdings_snapshot.clone();
                    carried_forward_state.snapshot_date = current_date;
                    carried_forward_state.id =
                        format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                    // Note: calculated_at remains the same as the previous snapshot
                    current_holdings_snapshot = carried_forward_state;
                } else {
                    // Activities occurred, call the calculator
                    match self
                        .holdings_calculator
                        .calculate_next_holdings_for_account_type(
                            run,
                            previous_holdings_snapshot,
                            &activities_today, // Pass the already fetched activities
                            current_date,
                            Some(&account.account_type),
                        ) {
                        Ok(calc_result) => {
                            // Collect any warnings from activity processing
                            if calc_result.has_warnings() {
                                for warning in &calc_result.warnings {
                                    warn!(
                                        "Holdings calculation warning for account {} on {}: {}",
                                        account_id, current_date, warning
                                    );
                                }
                                all_warnings.extend(calc_result.warnings);
                            }

                            // Calculator provides the new state, including updated calculated_at
                            current_holdings_snapshot = calc_result.snapshot;

                            debug!(
                                "Holdings calculated successfully for account {} on {}",
                                account_id, current_date
                            );
                        }
                        Err(e) => {
                            error!(
                                "Holdings calculation failed for account {} on {}: {}. Carrying forward previous state.",
                                account_id, current_date, e
                            );
                            // Carry forward the previous day's state on error
                            let mut errored_state = previous_holdings_snapshot.clone();
                            errored_state.snapshot_date = current_date; // Update date even if carried forward
                            errored_state.id =
                                format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                            // calculated_at remains the same as the previous snapshot
                            current_holdings_snapshot = errored_state;
                        }
                    }
                }

                // Decide if it's a keyframe based on the determined snapshot
                // A keyframe is needed on the first day of calculation or if activities happened.
                let is_keyframe = is_first_day || has_activities;

                if is_keyframe {
                    // Create the keyframe based on the final state for today
                    let mut keyframe_snapshot = current_holdings_snapshot.clone();
                    // Ensure account_id and id are correctly set for the keyframe
                    keyframe_snapshot.account_id = account_id.clone();
                    keyframe_snapshot.id =
                        format!("{}_{}", account_id, current_date.format("%Y-%m-%d"));
                    keyframes_today.push(keyframe_snapshot);
                }

                // Store the calculated/carried-forward snapshot for the next iteration's "previous" state
                next_day_holdings_snapshots
                    .insert(account_id.to_string(), current_holdings_snapshot); // Use the final determined snapshot
            }

            // Update the main state map for the next day
            // Important: Only update states for accounts processed today.
            for (id, state) in next_day_holdings_snapshots {
                current_holdings_snapshots.insert(id, state);
            }
            keyframes_to_save.extend(keyframes_today);
        }

        // Log summary of warnings if any occurred
        if !all_warnings.is_empty() {
            warn!(
                "Holdings calculation completed with {} warning(s) for activities that could not be processed",
                all_warnings.len()
            );
        }

        // Return the final holdings states, keyframes, and any warnings
        Ok((current_holdings_snapshots, keyframes_to_save, all_warnings))
    }

    // --- Helpers ---

    // create_initial_snapshot creates a snapshot with default values
    fn create_initial_snapshot(account: &Account, date: NaiveDate) -> AccountStateSnapshot {
        AccountStateSnapshot {
            id: AccountStateSnapshot::stable_id(&account.id, date),
            account_id: account.id.clone(),
            snapshot_date: date,
            currency: account.currency.clone(),
            positions: HashMap::new(),
            cash_balances: HashMap::new(),
            cost_basis: Decimal::ZERO,
            net_contribution: Decimal::ZERO,
            net_contribution_base: Decimal::ZERO,
            cash_total_account_currency: Decimal::ZERO,
            cash_total_base_currency: Decimal::ZERO,
            calculated_at: Utc::now().naive_utc(),
            source: SnapshotSource::Calculated,
        }
    }

    // (Helper function group_activities_by_account_and_date moved inside preprocess_data)

    // `calculate_split_factors` and `adjust_activities_for_splits` were removed:
    // splits are now tracked per-lot via the immutable `split_ratio` field
    // (see `positions_model::Position::apply_split`). Pre-adjusting historical
    // BUY/SELL quantities and prices for subsequent splits, on top of the
    // per-lot ratio that the calculator now applies, would double-apply the
    // split factor.
}

#[cfg(test)]
impl SnapshotService {
    pub fn get_daily_holdings_snapshots(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>> {
        let timeline = self.get_holdings_timeline(account_id, start_date, end_date)?;
        Ok(timeline
            .iter()
            .map(|day| {
                let mut snapshot = day.snapshot.clone();
                snapshot.snapshot_date = day.date;
                snapshot.id = AccountStateSnapshot::stable_id(account_id, day.date);
                snapshot
            })
            .collect())
    }
}

#[async_trait]
impl SnapshotServiceTrait for SnapshotService {
    async fn recalculate_holdings_snapshots(
        &self,
        account_ids: Option<&[String]>,
        mode: SnapshotRecalcMode,
    ) -> Result<usize> {
        self.calculate_holdings_snapshots_internal(account_ids, mode)
            .await
    }

    fn get_holdings_keyframes(
        &self,
        account_id: &str,
        start_date_opt: Option<NaiveDate>,
        end_date_opt: Option<NaiveDate>,
    ) -> Result<Vec<AccountStateSnapshot>> {
        debug!(
            "Getting saved holdings keyframes for {} from {:?} to {:?}",
            account_id, start_date_opt, end_date_opt
        );
        // Directly fetch from the repository without reconstruction
        self.snapshot_repository
            .get_snapshots_by_account(account_id, start_date_opt, end_date_opt)
    }

    fn get_holdings_timeline(
        &self,
        account_id: &str,
        start_date_opt: Option<NaiveDate>,
        end_date_opt: Option<NaiveDate>,
    ) -> Result<HoldingsTimeline> {
        debug!(
            "Building holdings timeline for {} from {:?} to {:?}",
            account_id, start_date_opt, end_date_opt
        );

        let today = self.user_today();
        if let Some(start_date) = start_date_opt {
            validate_snapshot_read_date(
                account_id,
                start_date,
                SnapshotSource::Calculated.as_str(),
                today,
            )?;
        }
        if let Some(end_date) = end_date_opt {
            validate_snapshot_read_date(
                account_id,
                end_date,
                SnapshotSource::Calculated.as_str(),
                today,
            )?;
        }
        let all_keyframes = self
            .snapshot_repository
            .get_snapshots_by_account(account_id, None, None)?;
        let deferred_future_snapshots = all_keyframes
            .iter()
            .any(|snapshot| snapshot.snapshot_date > today);
        for snapshot in &all_keyframes {
            validate_snapshot_read_date(
                account_id,
                snapshot.snapshot_date,
                snapshot.source.as_str(),
                today,
            )?;
        }
        let eligible_keyframes: Vec<_> = all_keyframes
            .into_iter()
            .filter(|snapshot| snapshot.snapshot_date <= today)
            .collect();
        // Match the former dense engine's BTreeMap behavior: for duplicate dates,
        // the last repository row wins.
        let eligible_keyframes: Vec<_> = eligible_keyframes
            .into_iter()
            .map(|snapshot| (snapshot.snapshot_date, snapshot))
            .collect::<BTreeMap<_, _>>()
            .into_values()
            .collect();
        let earliest_snapshot_date = eligible_keyframes
            .iter()
            .map(|snapshot| snapshot.snapshot_date)
            .min();

        let start_date = match start_date_opt {
            Some(date) => date,
            None => match earliest_snapshot_date {
                Some(date) => date,
                None => {
                    debug!(
                        "No snapshots found for account {}. Returning empty.",
                        account_id
                    );
                    return Ok(HoldingsTimeline::new(
                        None,
                        today,
                        Vec::new(),
                        None,
                        deferred_future_snapshots,
                    ));
                }
            },
        };

        let end_date = end_date_opt.unwrap_or(today).min(today);

        if start_date > end_date {
            warn!(
                "get_holdings_timeline: Start date {} is after end date {}. Returning empty.",
                start_date, end_date
            );
            return Ok(HoldingsTimeline::new(
                None,
                end_date,
                Vec::new(),
                None,
                deferred_future_snapshots,
            ));
        }

        let anchor = eligible_keyframes
            .iter()
            .filter(|snapshot| snapshot.snapshot_date <= start_date)
            .max_by_key(|snapshot| snapshot.snapshot_date)
            .cloned();
        let mut timeline_keyframes = Vec::new();
        if let Some(anchor) = anchor {
            timeline_keyframes.push(anchor);
        }
        timeline_keyframes.extend(eligible_keyframes.into_iter().filter(|snapshot| {
            snapshot.snapshot_date > start_date && snapshot.snapshot_date <= end_date
        }));
        timeline_keyframes.sort_by_key(|snapshot| snapshot.snapshot_date);

        if timeline_keyframes.is_empty() {
            return Ok(HoldingsTimeline::new(
                None,
                end_date,
                Vec::new(),
                None,
                deferred_future_snapshots,
            ));
        }

        let empty_state = if timeline_keyframes
            .first()
            .is_some_and(|snapshot| snapshot.snapshot_date > start_date)
        {
            let account = self.account_repository.get_by_id(account_id).map_err(|_| {
                Error::Repository(format!(
                    "Account not found while building holdings timeline: {}",
                    account_id
                ))
            })?;
            Some(Self::create_initial_snapshot(
                &account,
                start_date.pred_opt().unwrap_or(start_date),
            ))
        } else {
            None
        };

        Ok(HoldingsTimeline::new(
            Some(start_date),
            end_date,
            timeline_keyframes,
            empty_state,
            deferred_future_snapshots,
        ))
    }

    fn get_latest_holdings_snapshot(
        &self,
        account_id: &str,
    ) -> Result<Option<AccountStateSnapshot>> {
        let today = self.user_today();
        // The date passed to get_latest_snapshot_before_date is exclusive, so use tomorrow to include today.
        let tomorrow = today.succ_opt().unwrap_or(today);
        match self
            .snapshot_repository
            .get_latest_snapshot_before_date(account_id, tomorrow)?
        {
            Some(snapshot) => Ok(Some(snapshot)),
            None => {
                // It's possible no snapshot exists yet, which is not necessarily an error,
                // but we should inform the caller.
                debug!(
                    "No snapshot found for account {} on or before {}",
                    account_id, today
                );
                Ok(None)
            }
        }
    }

    async fn save_manual_snapshot(
        &self,
        account_id: &str,
        mut snapshot: AccountStateSnapshot,
    ) -> Result<()> {
        // Ensure the snapshot has the correct account_id
        snapshot.account_id = account_id.to_string();

        validate_snapshot_write_date(
            account_id,
            snapshot.snapshot_date,
            snapshot.source.as_str(),
            self.user_today(),
        )?;

        // Note: snapshot.source is preserved from the caller (ManualEntry or CsvImport)

        // Generate the snapshot ID based on account_id and date
        snapshot.id = AccountStateSnapshot::stable_id(account_id, snapshot.snapshot_date);

        // Check if content is unchanged from existing snapshot on the same date (skip if identical)
        // Only compare against the same date because stable IDs are date-based.
        let same_date_snapshots = self.snapshot_repository.get_snapshots_by_account(
            account_id,
            Some(snapshot.snapshot_date),
            Some(snapshot.snapshot_date),
        )?;

        if let Some(existing) = same_date_snapshots.into_iter().next() {
            if existing.is_content_equal(&snapshot) {
                debug!(
                    "Snapshot content unchanged for account {} on {}, skipping save",
                    account_id, snapshot.snapshot_date
                );
                // ManualSnapshotService may already have updated quote mode or
                // persisted a manual quote before this snapshot-level no-op.
                // Keep the dated recalculation signal even when the snapshot
                // row itself does not need to be rewritten.
                let asset_ids: Vec<String> = snapshot
                    .positions
                    .values()
                    .map(|position| position.asset_id.clone())
                    .collect();
                self.emit_holdings_changed(
                    vec![account_id.to_string()],
                    asset_ids,
                    snapshot.snapshot_date,
                );
                return Ok(());
            }
        }

        // Update the calculated_at timestamp
        snapshot.calculated_at = Utc::now().naive_utc();

        // Save or update the snapshot using repository method
        self.snapshot_repository
            .save_or_update_snapshot(&snapshot)
            .await?;

        info!(
            "Saved manual snapshot for account {} on date {}",
            account_id, snapshot.snapshot_date
        );

        // Emit HoldingsChanged event after successful save
        let asset_ids: Vec<String> = snapshot
            .positions
            .values()
            .map(|p| p.asset_id.clone())
            .collect();
        self.emit_holdings_changed(
            vec![account_id.to_string()],
            asset_ids,
            snapshot.snapshot_date,
        );

        Ok(())
    }

    async fn update_snapshots_source(&self, account_id: &str, new_source: &str) -> Result<usize> {
        debug!(
            "Updating snapshot source for account {} to {}",
            account_id, new_source
        );

        let updated_count = self
            .snapshot_repository
            .update_snapshots_source(account_id, new_source)
            .await?;

        info!(
            "Updated {} snapshots for account {} to source {}",
            updated_count, account_id, new_source
        );

        Ok(updated_count)
    }

    async fn delete_snapshot_for_account(
        &self,
        account_id: &str,
        dates: &[NaiveDate],
    ) -> Result<()> {
        self.snapshot_repository
            .delete_snapshots_for_account_and_dates(account_id, dates)
            .await?;
        Ok(())
    }

    fn get_snapshot_metadata(
        &self,
        account_id: &str,
        start_date: Option<NaiveDate>,
        end_date: Option<NaiveDate>,
    ) -> Result<Vec<SnapshotMetadata>> {
        self.snapshot_repository
            .get_snapshot_metadata_by_account(account_id, start_date, end_date)
    }

    async fn delete_snapshot_for_account_by_id(
        &self,
        account_id: &str,
        snapshot_id: &str,
    ) -> Result<()> {
        self.snapshot_repository
            .delete_snapshot_for_account_by_id(account_id, snapshot_id)
            .await
    }
}

/// Orders accounts for a given day so that TRANSFER_OUT sources are processed
/// before their paired TRANSFER_IN destinations. Uses topological sort (Kahn's
/// algorithm) on edges derived from `source_group_id` to handle chains (A→B→C).
/// Accounts without transfer dependencies retain their original order.
fn order_accounts_by_transfer_deps<'a>(
    accounts: &'a AccountsMap,
    activities_by_account_date: &ActivitiesByAccount,
    effective_start_dates: &StartDatesMap,
    current_date: NaiveDate,
) -> Vec<(&'a String, &'a Account)> {
    let eligible: Vec<(&String, &Account)> = accounts
        .iter()
        .filter(|(id, _)| {
            effective_start_dates
                .get(*id)
                .is_some_and(|start| *start <= current_date)
        })
        .collect();

    let n = eligible.len();
    if n <= 1 {
        return eligible;
    }

    // Map account_id → index
    let idx_of: HashMap<&str, usize> = eligible
        .iter()
        .enumerate()
        .map(|(i, (id, _))| (id.as_str(), i))
        .collect();

    // Scan today's activities to find source_group_id → (OUT account, IN account) pairs
    let mut out_idx_for_group: HashMap<String, usize> = HashMap::new();
    let mut in_idx_for_group: HashMap<String, usize> = HashMap::new();

    for (account_id, _) in &eligible {
        if let Some(activities) = activities_by_account_date
            .get(account_id.as_str())
            .and_then(|dates| dates.get(&current_date))
        {
            let acct_idx = idx_of[account_id.as_str()];
            for a in activities {
                if let Some(ref gid) = a.source_group_id {
                    if a.activity_type == "TRANSFER_OUT" {
                        out_idx_for_group.insert(gid.clone(), acct_idx);
                    } else if a.activity_type == "TRANSFER_IN" {
                        in_idx_for_group.insert(gid.clone(), acct_idx);
                    }
                }
            }
        }
    }

    // Build adjacency: out_account must be processed before in_account
    let mut successors: Vec<Vec<usize>> = vec![vec![]; n];
    let mut in_degree: Vec<u32> = vec![0; n];
    let mut has_edges = false;

    for (gid, &out_idx) in &out_idx_for_group {
        if let Some(&in_idx) = in_idx_for_group.get(gid) {
            if out_idx != in_idx {
                successors[out_idx].push(in_idx);
                in_degree[in_idx] += 1;
                has_edges = true;
            }
        }
    }

    if !has_edges {
        return eligible;
    }

    // Kahn's algorithm
    let mut queue: VecDeque<usize> = (0..n).filter(|&i| in_degree[i] == 0).collect();
    let mut order: Vec<usize> = Vec::with_capacity(n);

    while let Some(idx) = queue.pop_front() {
        order.push(idx);
        for &succ in &successors[idx] {
            in_degree[succ] -= 1;
            if in_degree[succ] == 0 {
                queue.push_back(succ);
            }
        }
    }

    // Append any remaining (would indicate a cycle — shouldn't happen in practice)
    if order.len() < n {
        let in_order: HashSet<usize> = order.iter().copied().collect();
        for i in 0..n {
            if !in_order.contains(&i) {
                order.push(i);
            }
        }
    }

    order.into_iter().map(|i| eligible[i]).collect()
}
